% 编译项目

clear TraderMain
includepath = '..\include';
libpath = '..\lib';
mex(['-I', includepath], ...
        ['-L', libpath], ...
        ['-l', 'thostmduserapi.lib'], ...
        ['-l', 'thosttraderapi.lib'], ...
        ['-l', 'FrameDll.lib'], ...
    'TraderMain.cpp', '..\include\DBLog.cpp', 'Trader.cpp', '..\include\toolkit.cpp', 'TraderCallback.cpp');
%移动到lib下运行
movefile('TraderMain.mexw32', '..\lib\TraderMain.mexw32');
clear includepath libpath
