from ctypes import *
TThostFtdcTraderIDType = c_char * 21
TThostFtdcInvestorIDType = c_char * 13
TThostFtdcBrokerIDType = c_char * 11
TThostFtdcBrokerAbbrType = c_char * 9
TThostFtdcBrokerNameType = c_char * 81
TThostFtdcExchangeInstIDType = c_char * 31
TThostFtdcOrderRefType = c_char * 13
TThostFtdcParticipantIDType = c_char * 11
TThostFtdcUserIDType = c_char * 16
TThostFtdcPasswordType = c_char * 41
TThostFtdcClientIDType = c_char * 11
TThostFtdcInstrumentIDType = c_char * 31
TThostFtdcMarketIDType = c_char * 31
TThostFtdcProductNameType = c_char * 21
TThostFtdcExchangeIDType = c_char * 9
TThostFtdcExchangeNameType = c_char * 61
TThostFtdcExchangeAbbrType = c_char * 9
TThostFtdcExchangeFlagType = c_char * 2
TThostFtdcMacAddressType = c_char * 21
TThostFtdcSystemIDType = c_char * 21
THOST_FTDC_EXP_Normal = '0'
THOST_FTDC_EXP_GenOrderByTrade = '1'
TThostFtdcExchangePropertyType = c_char
TThostFtdcDateType = c_char * 9
TThostFtdcTimeType = c_char * 9
TThostFtdcLongTimeType = c_char * 13
TThostFtdcInstrumentNameType = c_char * 21
TThostFtdcSettlementGroupIDType = c_char * 9
TThostFtdcOrderSysIDType = c_char * 21
TThostFtdcTradeIDType = c_char * 21
TThostFtdcCommandTypeType = c_char * 65
TThostFtdcIPAddressType = c_char * 16
TThostFtdcIPPortType = c_int
TThostFtdcProductInfoType = c_char * 11
TThostFtdcProtocolInfoType = c_char * 11
TThostFtdcBusinessUnitType = c_char * 21
TThostFtdcDepositSeqNoType = c_char * 15
TThostFtdcIdentifiedCardNoType = c_char * 51
THOST_FTDC_ICT_EID = '0'
THOST_FTDC_ICT_IDCard = '1'
THOST_FTDC_ICT_OfficerIDCard = '2'
THOST_FTDC_ICT_PoliceIDCard = '3'
THOST_FTDC_ICT_SoldierIDCard = '4'
THOST_FTDC_ICT_HouseholdRegister = '5'
THOST_FTDC_ICT_Passport = '6'
THOST_FTDC_ICT_TaiwanCompatriotIDCard = '7'
THOST_FTDC_ICT_HomeComingCard = '8'
THOST_FTDC_ICT_LicenseNo = '9'
THOST_FTDC_ICT_TaxNo = 'A'
THOST_FTDC_ICT_HMMainlandTravelPermit = 'B'
THOST_FTDC_ICT_TwMainlandTravelPermit = 'C'
THOST_FTDC_ICT_DrivingLicense = 'D'
THOST_FTDC_ICT_SocialID = 'F'
THOST_FTDC_ICT_LocalID = 'G'
THOST_FTDC_ICT_BusinessRegistration = 'H'
THOST_FTDC_ICT_HKMCIDCard = 'I'
THOST_FTDC_ICT_OtherCard = 'x'
TThostFtdcIdCardTypeType = c_char
TThostFtdcOrderLocalIDType = c_char * 13
TThostFtdcUserNameType = c_char * 81
TThostFtdcPartyNameType = c_char * 81
TThostFtdcErrorMsgType = c_char * 81
TThostFtdcFieldNameType = c_char * 2049
TThostFtdcFieldContentType = c_char * 2049
TThostFtdcSystemNameType = c_char * 41
TThostFtdcContentType = c_char * 501
THOST_FTDC_IR_All = '1'
THOST_FTDC_IR_Group = '2'
THOST_FTDC_IR_Single = '3'
TThostFtdcInvestorRangeType = c_char
THOST_FTDC_DR_All = '1'
THOST_FTDC_DR_Group = '2'
THOST_FTDC_DR_Single = '3'
TThostFtdcDepartmentRangeType = c_char
THOST_FTDC_DS_Asynchronous = '1'
THOST_FTDC_DS_Synchronizing = '2'
THOST_FTDC_DS_Synchronized = '3'
TThostFtdcDataSyncStatusType = c_char
THOST_FTDC_BDS_Synchronized = '1'
THOST_FTDC_BDS_Synchronizing = '2'
TThostFtdcBrokerDataSyncStatusType = c_char
THOST_FTDC_ECS_NoConnection = '1'
THOST_FTDC_ECS_QryInstrumentSent = '2'
THOST_FTDC_ECS_GotInformation = '9'
TThostFtdcExchangeConnectStatusType = c_char
THOST_FTDC_TCS_NotConnected = '1'
THOST_FTDC_TCS_Connected = '2'
THOST_FTDC_TCS_QryInstrumentSent = '3'
THOST_FTDC_TCS_SubPrivateFlow = '4'
TThostFtdcTraderConnectStatusType = c_char
THOST_FTDC_FC_DataAsync = '1'
THOST_FTDC_FC_ForceUserLogout = '2'
THOST_FTDC_FC_UserPasswordUpdate = '3'
THOST_FTDC_FC_BrokerPasswordUpdate = '4'
THOST_FTDC_FC_InvestorPasswordUpdate = '5'
THOST_FTDC_FC_OrderInsert = '6'
THOST_FTDC_FC_OrderAction = '7'
THOST_FTDC_FC_SyncSystemData = '8'
THOST_FTDC_FC_SyncBrokerData = '9'
THOST_FTDC_FC_BachSyncBrokerData = 'A'
THOST_FTDC_FC_SuperQuery = 'B'
THOST_FTDC_FC_ParkedOrderInsert = 'C'
THOST_FTDC_FC_ParkedOrderAction = 'D'
THOST_FTDC_FC_SyncOTP = 'E'
THOST_FTDC_FC_DeleteOrder = 'F'
TThostFtdcFunctionCodeType = c_char
THOST_FTDC_BFC_ForceUserLogout = '1'
THOST_FTDC_BFC_UserPasswordUpdate = '2'
THOST_FTDC_BFC_SyncBrokerData = '3'
THOST_FTDC_BFC_BachSyncBrokerData = '4'
THOST_FTDC_BFC_OrderInsert = '5'
THOST_FTDC_BFC_OrderAction = '6'
THOST_FTDC_BFC_AllQuery = '7'
THOST_FTDC_BFC_log = 'a'
THOST_FTDC_BFC_BaseQry = 'b'
THOST_FTDC_BFC_TradeQry = 'c'
THOST_FTDC_BFC_Trade = 'd'
THOST_FTDC_BFC_Virement = 'e'
THOST_FTDC_BFC_Risk = 'f'
THOST_FTDC_BFC_Session = 'g'
THOST_FTDC_BFC_RiskNoticeCtl = 'h'
THOST_FTDC_BFC_RiskNotice = 'i'
THOST_FTDC_BFC_BrokerDeposit = 'j'
THOST_FTDC_BFC_QueryFund = 'k'
THOST_FTDC_BFC_QueryOrder = 'l'
THOST_FTDC_BFC_QueryTrade = 'm'
THOST_FTDC_BFC_QueryPosition = 'n'
THOST_FTDC_BFC_QueryMarketData = 'o'
THOST_FTDC_BFC_QueryUserEvent = 'p'
THOST_FTDC_BFC_QueryRiskNotify = 'q'
THOST_FTDC_BFC_QueryFundChange = 'r'
THOST_FTDC_BFC_QueryInvestor = 's'
THOST_FTDC_BFC_QueryTradingCode = 't'
THOST_FTDC_BFC_ForceClose = 'u'
THOST_FTDC_BFC_PressTest = 'v'
THOST_FTDC_BFC_RemainCalc = 'w'
THOST_FTDC_BFC_NetPositionInd = 'x'
THOST_FTDC_BFC_RiskPredict = 'y'
THOST_FTDC_BFC_DataExport = 'z'
THOST_FTDC_BFC_RiskTargetSetup = 'A'
THOST_FTDC_BFC_MarketDataWarn = 'B'
THOST_FTDC_BFC_QryBizNotice = 'C'
THOST_FTDC_BFC_CfgBizNotice = 'D'
THOST_FTDC_BFC_SyncOTP = 'E'
THOST_FTDC_BFC_SendBizNotice = 'F'
THOST_FTDC_BFC_CfgRiskLevelStd = 'G'
THOST_FTDC_BFC_TbCommand = 'H'
THOST_FTDC_BFC_DeleteOrder = 'J'
THOST_FTDC_BFC_ParkedOrderInsert = 'K'
THOST_FTDC_BFC_ParkedOrderAction = 'L'
TThostFtdcBrokerFunctionCodeType = c_char
THOST_FTDC_OAS_Submitted = 'a'
THOST_FTDC_OAS_Accepted = 'b'
THOST_FTDC_OAS_Rejected = 'c'
TThostFtdcOrderActionStatusType = c_char
THOST_FTDC_OST_AllTraded = '0'
THOST_FTDC_OST_PartTradedQueueing = '1'
THOST_FTDC_OST_PartTradedNotQueueing = '2'
THOST_FTDC_OST_NoTradeQueueing = '3'
THOST_FTDC_OST_NoTradeNotQueueing = '4'
THOST_FTDC_OST_Canceled = '5'
THOST_FTDC_OST_Unknown = 'a'
THOST_FTDC_OST_NotTouched = 'b'
THOST_FTDC_OST_Touched = 'c'
TThostFtdcOrderStatusType = c_char
THOST_FTDC_OSS_InsertSubmitted = '0'
THOST_FTDC_OSS_CancelSubmitted = '1'
THOST_FTDC_OSS_ModifySubmitted = '2'
THOST_FTDC_OSS_Accepted = '3'
THOST_FTDC_OSS_InsertRejected = '4'
THOST_FTDC_OSS_CancelRejected = '5'
THOST_FTDC_OSS_ModifyRejected = '6'
TThostFtdcOrderSubmitStatusType = c_char
THOST_FTDC_PSD_Today = '1'
THOST_FTDC_PSD_History = '2'
TThostFtdcPositionDateType = c_char
THOST_FTDC_PDT_UseHistory = '1'
THOST_FTDC_PDT_NoUseHistory = '2'
TThostFtdcPositionDateTypeType = c_char
THOST_FTDC_ER_Broker = '1'
THOST_FTDC_ER_Host = '2'
THOST_FTDC_ER_Maker = '3'
TThostFtdcTradingRoleType = c_char
THOST_FTDC_PC_Futures = '1'
THOST_FTDC_PC_Options = '2'
THOST_FTDC_PC_Combination = '3'
THOST_FTDC_PC_Spot = '4'
THOST_FTDC_PC_EFP = '5'
THOST_FTDC_PC_SpotOption = '6'
TThostFtdcProductClassType = c_char
THOST_FTDC_IP_NotStart = '0'
THOST_FTDC_IP_Started = '1'
THOST_FTDC_IP_Pause = '2'
THOST_FTDC_IP_Expired = '3'
TThostFtdcInstLifePhaseType = c_char
THOST_FTDC_D_Buy = '0'
THOST_FTDC_D_Sell = '1'
TThostFtdcDirectionType = c_char
THOST_FTDC_PT_Net = '1'
THOST_FTDC_PT_Gross = '2'
TThostFtdcPositionTypeType = c_char
THOST_FTDC_PD_Net = '1'
THOST_FTDC_PD_Long = '2'
THOST_FTDC_PD_Short = '3'
TThostFtdcPosiDirectionType = c_char
THOST_FTDC_SS_NonActive = '1'
THOST_FTDC_SS_Startup = '2'
THOST_FTDC_SS_Operating = '3'
THOST_FTDC_SS_Settlement = '4'
THOST_FTDC_SS_SettlementFinished = '5'
TThostFtdcSysSettlementStatusType = c_char
THOST_FTDC_RA_Trade = '0'
THOST_FTDC_RA_Settlement = '1'
TThostFtdcRatioAttrType = c_char
THOST_FTDC_HF_Speculation = '1'
THOST_FTDC_HF_Arbitrage = '2'
THOST_FTDC_HF_Hedge = '3'
TThostFtdcHedgeFlagType = c_char
THOST_FTDC_BHF_Speculation = '1'
THOST_FTDC_BHF_Arbitrage = '2'
THOST_FTDC_BHF_Hedge = '3'
TThostFtdcBillHedgeFlagType = c_char
THOST_FTDC_CIDT_Speculation = '1'
THOST_FTDC_CIDT_Arbitrage = '2'
THOST_FTDC_CIDT_Hedge = '3'
TThostFtdcClientIDTypeType = c_char
THOST_FTDC_OPT_AnyPrice = '1'
THOST_FTDC_OPT_LimitPrice = '2'
THOST_FTDC_OPT_BestPrice = '3'
THOST_FTDC_OPT_LastPrice = '4'
THOST_FTDC_OPT_LastPricePlusOneTicks = '5'
THOST_FTDC_OPT_LastPricePlusTwoTicks = '6'
THOST_FTDC_OPT_LastPricePlusThreeTicks = '7'
THOST_FTDC_OPT_AskPrice1 = '8'
THOST_FTDC_OPT_AskPrice1PlusOneTicks = '9'
THOST_FTDC_OPT_AskPrice1PlusTwoTicks = 'A'
THOST_FTDC_OPT_AskPrice1PlusThreeTicks = 'B'
THOST_FTDC_OPT_BidPrice1 = 'C'
THOST_FTDC_OPT_BidPrice1PlusOneTicks = 'D'
THOST_FTDC_OPT_BidPrice1PlusTwoTicks = 'E'
THOST_FTDC_OPT_BidPrice1PlusThreeTicks = 'F'
TThostFtdcOrderPriceTypeType = c_char
THOST_FTDC_OF_Open = '0'
THOST_FTDC_OF_Close = '1'
THOST_FTDC_OF_ForceClose = '2'
THOST_FTDC_OF_CloseToday = '3'
THOST_FTDC_OF_CloseYesterday = '4'
THOST_FTDC_OF_ForceOff = '5'
THOST_FTDC_OF_LocalForceClose = '6'
TThostFtdcOffsetFlagType = c_char
THOST_FTDC_FCC_NotForceClose = '0'
THOST_FTDC_FCC_LackDeposit = '1'
THOST_FTDC_FCC_ClientOverPositionLimit = '2'
THOST_FTDC_FCC_MemberOverPositionLimit = '3'
THOST_FTDC_FCC_NotMultiple = '4'
THOST_FTDC_FCC_Violation = '5'
THOST_FTDC_FCC_Other = '6'
THOST_FTDC_FCC_PersonDeliv = '7'
TThostFtdcForceCloseReasonType = c_char
THOST_FTDC_ORDT_Normal = '0'
THOST_FTDC_ORDT_DeriveFromQuote = '1'
THOST_FTDC_ORDT_DeriveFromCombination = '2'
THOST_FTDC_ORDT_Combination = '3'
THOST_FTDC_ORDT_ConditionalOrder = '4'
THOST_FTDC_ORDT_Swap = '5'
TThostFtdcOrderTypeType = c_char
THOST_FTDC_TC_IOC = '1'
THOST_FTDC_TC_GFS = '2'
THOST_FTDC_TC_GFD = '3'
THOST_FTDC_TC_GTD = '4'
THOST_FTDC_TC_GTC = '5'
THOST_FTDC_TC_GFA = '6'
TThostFtdcTimeConditionType = c_char
THOST_FTDC_VC_AV = '1'
THOST_FTDC_VC_MV = '2'
THOST_FTDC_VC_CV = '3'
TThostFtdcVolumeConditionType = c_char
THOST_FTDC_CC_Immediately = '1'
THOST_FTDC_CC_Touch = '2'
THOST_FTDC_CC_TouchProfit = '3'
THOST_FTDC_CC_ParkedOrder = '4'
THOST_FTDC_CC_LastPriceGreaterThanStopPrice = '5'
THOST_FTDC_CC_LastPriceGreaterEqualStopPrice = '6'
THOST_FTDC_CC_LastPriceLesserThanStopPrice = '7'
THOST_FTDC_CC_LastPriceLesserEqualStopPrice = '8'
THOST_FTDC_CC_AskPriceGreaterThanStopPrice = '9'
THOST_FTDC_CC_AskPriceGreaterEqualStopPrice = 'A'
THOST_FTDC_CC_AskPriceLesserThanStopPrice = 'B'
THOST_FTDC_CC_AskPriceLesserEqualStopPrice = 'C'
THOST_FTDC_CC_BidPriceGreaterThanStopPrice = 'D'
THOST_FTDC_CC_BidPriceGreaterEqualStopPrice = 'E'
THOST_FTDC_CC_BidPriceLesserThanStopPrice = 'F'
THOST_FTDC_CC_BidPriceLesserEqualStopPrice = 'H'
TThostFtdcContingentConditionType = c_char
THOST_FTDC_AF_Delete = '0'
THOST_FTDC_AF_Modify = '3'
TThostFtdcActionFlagType = c_char
THOST_FTDC_TR_Allow = '0'
THOST_FTDC_TR_CloseOnly = '1'
THOST_FTDC_TR_Forbidden = '2'
TThostFtdcTradingRightType = c_char
THOST_FTDC_OSRC_Participant = '0'
THOST_FTDC_OSRC_Administrator = '1'
TThostFtdcOrderSourceType = c_char
THOST_FTDC_TRDT_SplitCombination = '#'
THOST_FTDC_TRDT_Common = '0'
THOST_FTDC_TRDT_OptionsExecution = '1'
THOST_FTDC_TRDT_OTC = '2'
THOST_FTDC_TRDT_EFPDerived = '3'
THOST_FTDC_TRDT_CombinationDerived = '4'
TThostFtdcTradeTypeType = c_char
THOST_FTDC_PSRC_LastPrice = '0'
THOST_FTDC_PSRC_Buy = '1'
THOST_FTDC_PSRC_Sell = '2'
TThostFtdcPriceSourceType = c_char
THOST_FTDC_IS_BeforeTrading = '0'
THOST_FTDC_IS_NoTrading = '1'
THOST_FTDC_IS_Continous = '2'
THOST_FTDC_IS_AuctionOrdering = '3'
THOST_FTDC_IS_AuctionBalance = '4'
THOST_FTDC_IS_AuctionMatch = '5'
THOST_FTDC_IS_Closed = '6'
TThostFtdcInstrumentStatusType = c_char
THOST_FTDC_IER_Automatic = '1'
THOST_FTDC_IER_Manual = '2'
THOST_FTDC_IER_Fuse = '3'
TThostFtdcInstStatusEnterReasonType = c_char
TThostFtdcOrderActionRefType = c_int
TThostFtdcInstallCountType = c_int
TThostFtdcInstallIDType = c_int
TThostFtdcErrorIDType = c_int
TThostFtdcSettlementIDType = c_int
TThostFtdcVolumeType = c_int
TThostFtdcFrontIDType = c_int
TThostFtdcSessionIDType = c_int
TThostFtdcSequenceNoType = c_int
TThostFtdcCommandNoType = c_int
TThostFtdcMillisecType = c_int
TThostFtdcVolumeMultipleType = c_int
TThostFtdcTradingSegmentSNType = c_int
TThostFtdcRequestIDType = c_int
TThostFtdcYearType = c_int
TThostFtdcMonthType = c_int
TThostFtdcBoolType = c_int
TThostFtdcPriceType = c_double
TThostFtdcCombOffsetFlagType = c_char * 5
TThostFtdcCombHedgeFlagType = c_char * 5
TThostFtdcRatioType = c_double
TThostFtdcMoneyType = c_double
TThostFtdcLargeVolumeType = c_double
TThostFtdcSequenceSeriesType = c_short
TThostFtdcCommPhaseNoType = c_short
TThostFtdcSequenceLabelType = c_char * 2
TThostFtdcUnderlyingMultipleType = c_double
TThostFtdcPriorityType = c_int
TThostFtdcContractCodeType = c_char * 41
TThostFtdcCityType = c_char * 51
TThostFtdcIsStockType = c_char * 11
TThostFtdcChannelType = c_char * 51
TThostFtdcAddressType = c_char * 101
TThostFtdcZipCodeType = c_char * 7
TThostFtdcTelephoneType = c_char * 41
TThostFtdcFaxType = c_char * 41
TThostFtdcMobileType = c_char * 41
TThostFtdcEMailType = c_char * 41
TThostFtdcMemoType = c_char * 161
TThostFtdcCompanyCodeType = c_char * 51
TThostFtdcWebsiteType = c_char * 51
TThostFtdcTaxNoType = c_char * 31
THOST_FTDC_BS_NoUpload = '1'
THOST_FTDC_BS_Uploaded = '2'
THOST_FTDC_BS_Failed = '3'
TThostFtdcBatchStatusType = c_char
TThostFtdcPropertyIDType = c_char * 33
TThostFtdcPropertyNameType = c_char * 65
TThostFtdcLicenseNoType = c_char * 51
TThostFtdcAgentIDType = c_char * 13
TThostFtdcAgentNameType = c_char * 41
TThostFtdcAgentGroupIDType = c_char * 13
TThostFtdcAgentGroupNameType = c_char * 41
THOST_FTDC_RS_All = '1'
THOST_FTDC_RS_ByProduct = '2'
TThostFtdcReturnStyleType = c_char
THOST_FTDC_RP_ByVolume = '1'
THOST_FTDC_RP_ByFeeOnHand = '2'
TThostFtdcReturnPatternType = c_char
THOST_FTDC_RL_Level1 = '1'
THOST_FTDC_RL_Level2 = '2'
THOST_FTDC_RL_Level3 = '3'
THOST_FTDC_RL_Level4 = '4'
THOST_FTDC_RL_Level5 = '5'
THOST_FTDC_RL_Level6 = '6'
THOST_FTDC_RL_Level7 = '7'
THOST_FTDC_RL_Level8 = '8'
THOST_FTDC_RL_Level9 = '9'
TThostFtdcReturnLevelType = c_char
THOST_FTDC_RSD_ByPeriod = '1'
THOST_FTDC_RSD_ByStandard = '2'
TThostFtdcReturnStandardType = c_char
THOST_FTDC_MT_Out = '0'
THOST_FTDC_MT_In = '1'
TThostFtdcMortgageTypeType = c_char
THOST_FTDC_ISPI_MortgageRatio = '4'
THOST_FTDC_ISPI_MarginWay = '5'
THOST_FTDC_ISPI_BillDeposit = '9'
TThostFtdcInvestorSettlementParamIDType = c_char
THOST_FTDC_ESPI_MortgageRatio = '1'
THOST_FTDC_ESPI_OtherFundItem = '2'
THOST_FTDC_ESPI_OtherFundImport = '3'
THOST_FTDC_ESPI_CFFEXMinPrepa = '6'
THOST_FTDC_ESPI_CZCESettlementType = '7'
THOST_FTDC_ESPI_ExchDelivFeeMode = '9'
THOST_FTDC_ESPI_DelivFeeMode = '0'
THOST_FTDC_ESPI_CZCEComMarginType = 'A'
THOST_FTDC_ESPI_DceComMarginType = 'B'
THOST_FTDC_ESPI_OptOutDisCountRate = 'a'
THOST_FTDC_ESPI_OptMiniGuarantee = 'b'
TThostFtdcExchangeSettlementParamIDType = c_char
THOST_FTDC_SPI_InvestorIDMinLength = '1'
THOST_FTDC_SPI_AccountIDMinLength = '2'
THOST_FTDC_SPI_UserRightLogon = '3'
THOST_FTDC_SPI_SettlementBillTrade = '4'
THOST_FTDC_SPI_TradingCode = '5'
THOST_FTDC_SPI_CheckFund = '6'
THOST_FTDC_SPI_CommModelRight = '7'
THOST_FTDC_SPI_MarginModelRight = '9'
THOST_FTDC_SPI_IsStandardActive = '8'
THOST_FTDC_SPI_UploadSettlementFile = 'U'
THOST_FTDC_SPI_DownloadCSRCFile = 'D'
THOST_FTDC_SPI_SettlementBillFile = 'S'
THOST_FTDC_SPI_CSRCOthersFile = 'C'
THOST_FTDC_SPI_InvestorPhoto = 'P'
THOST_FTDC_SPI_CSRCData = 'R'
THOST_FTDC_SPI_InvestorPwdModel = 'I'
THOST_FTDC_SPI_CFFEXInvestorSettleFile = 'F'
THOST_FTDC_SPI_InvestorIDType = 'a'
THOST_FTDC_SPI_FreezeMaxReMain = 'r'
THOST_FTDC_SPI_IsSync = 'A'
THOST_FTDC_SPI_RelieveOpenLimit = 'O'
THOST_FTDC_SPI_IsStandardFreeze = 'X'
THOST_FTDC_SPI_CZCENormalProductHedge = 'B'
TThostFtdcSystemParamIDType = c_char
THOST_FTDC_TPID_EncryptionStandard = 'E'
THOST_FTDC_TPID_RiskMode = 'R'
THOST_FTDC_TPID_RiskModeGlobal = 'G'
THOST_FTDC_TPID_modeEncode = 'P'
THOST_FTDC_TPID_tickMode = 'T'
THOST_FTDC_TPID_SingleUserSessionMaxNum = 'S'
THOST_FTDC_TPID_LoginFailMaxNum = 'L'
THOST_FTDC_TPID_IsAuthForce = 'A'
TThostFtdcTradeParamIDType = c_char
TThostFtdcSettlementParamValueType = c_char * 256
TThostFtdcCounterIDType = c_char * 33
TThostFtdcInvestorGroupNameType = c_char * 41
TThostFtdcBrandCodeType = c_char * 257
TThostFtdcWarehouseType = c_char * 257
TThostFtdcProductDateType = c_char * 41
TThostFtdcGradeType = c_char * 41
TThostFtdcClassifyType = c_char * 41
TThostFtdcPositionType = c_char * 41
TThostFtdcYieldlyType = c_char * 41
TThostFtdcWeightType = c_char * 41
TThostFtdcSubEntryFundNoType = c_int
THOST_FTDC_FI_SettlementFund = 'F'
THOST_FTDC_FI_Trade = 'T'
THOST_FTDC_FI_InvestorPosition = 'P'
THOST_FTDC_FI_SubEntryFund = 'O'
THOST_FTDC_FI_CZCECombinationPos = 'C'
THOST_FTDC_FI_CSRCData = 'R'
THOST_FTDC_FI_CZCEClose = 'L'
THOST_FTDC_FI_CZCENoClose = 'N'
THOST_FTDC_FI_PositionDtl = 'D'
THOST_FTDC_FI_OptionStrike = 'S'
THOST_FTDC_FI_SettlementPriceComparison = 'M'
THOST_FTDC_FI_NonTradePosChange = 'B'
TThostFtdcFileIDType = c_char
TThostFtdcFileNameType = c_char * 257
THOST_FTDC_FUT_Settlement = '0'
THOST_FTDC_FUT_Check = '1'
TThostFtdcFileTypeType = c_char
THOST_FTDC_FFT_Txt = '0'
THOST_FTDC_FFT_Zip = '1'
THOST_FTDC_FFT_DBF = '2'
TThostFtdcFileFormatType = c_char
THOST_FTDC_FUS_SucceedUpload = '1'
THOST_FTDC_FUS_FailedUpload = '2'
THOST_FTDC_FUS_SucceedLoad = '3'
THOST_FTDC_FUS_PartSucceedLoad = '4'
THOST_FTDC_FUS_FailedLoad = '5'
TThostFtdcFileUploadStatusType = c_char
THOST_FTDC_TD_Out = '0'
THOST_FTDC_TD_In = '1'
TThostFtdcTransferDirectionType = c_char
TThostFtdcUploadModeType = c_char * 21
TThostFtdcAccountIDType = c_char * 13
TThostFtdcBankFlagType = c_char * 4
TThostFtdcBankAccountType = c_char * 41
TThostFtdcOpenNameType = c_char * 61
TThostFtdcOpenBankType = c_char * 101
TThostFtdcBankNameType = c_char * 101
TThostFtdcPublishPathType = c_char * 257
TThostFtdcOperatorIDType = c_char * 65
TThostFtdcMonthCountType = c_int
TThostFtdcAdvanceMonthArrayType = c_char * 13
TThostFtdcDateExprType = c_char * 1025
TThostFtdcInstrumentIDExprType = c_char * 41
TThostFtdcInstrumentNameExprType = c_char * 41
THOST_FTDC_SC_NoSpecialRule = '0'
THOST_FTDC_SC_NoSpringFestival = '1'
TThostFtdcSpecialCreateRuleType = c_char
THOST_FTDC_IPT_LastSettlement = '1'
THOST_FTDC_IPT_LaseClose = '2'
TThostFtdcBasisPriceTypeType = c_char
THOST_FTDC_PLP_Active = '1'
THOST_FTDC_PLP_NonActive = '2'
THOST_FTDC_PLP_Canceled = '3'
TThostFtdcProductLifePhaseType = c_char
THOST_FTDC_DM_CashDeliv = '1'
THOST_FTDC_DM_CommodityDeliv = '2'
TThostFtdcDeliveryModeType = c_char
TThostFtdcLogLevelType = c_char * 33
TThostFtdcProcessNameType = c_char * 257
TThostFtdcOperationMemoType = c_char * 1025
THOST_FTDC_FIOT_FundIO = '1'
THOST_FTDC_FIOT_Transfer = '2'
THOST_FTDC_FIOT_SwapCurrency = '3'
TThostFtdcFundIOTypeType = c_char
THOST_FTDC_FT_Deposite = '1'
THOST_FTDC_FT_ItemFund = '2'
THOST_FTDC_FT_Company = '3'
THOST_FTDC_FT_InnerTransfer = '4'
TThostFtdcFundTypeType = c_char
THOST_FTDC_FD_In = '1'
THOST_FTDC_FD_Out = '2'
TThostFtdcFundDirectionType = c_char
THOST_FTDC_FS_Record = '1'
THOST_FTDC_FS_Check = '2'
THOST_FTDC_FS_Charge = '3'
TThostFtdcFundStatusType = c_char
TThostFtdcBillNoType = c_char * 15
TThostFtdcBillNameType = c_char * 33
THOST_FTDC_PS_None = '1'
THOST_FTDC_PS_Publishing = '2'
THOST_FTDC_PS_Published = '3'
TThostFtdcPublishStatusType = c_char
TThostFtdcEnumValueIDType = c_char * 65
TThostFtdcEnumValueTypeType = c_char * 33
TThostFtdcEnumValueLabelType = c_char * 65
TThostFtdcEnumValueResultType = c_char * 33
THOST_FTDC_ES_NonActive = '1'
THOST_FTDC_ES_Startup = '2'
THOST_FTDC_ES_Initialize = '3'
THOST_FTDC_ES_Initialized = '4'
THOST_FTDC_ES_Close = '5'
THOST_FTDC_ES_Closed = '6'
THOST_FTDC_ES_Settlement = '7'
TThostFtdcSystemStatusType = c_char
THOST_FTDC_STS_Initialize = '0'
THOST_FTDC_STS_Settlementing = '1'
THOST_FTDC_STS_Settlemented = '2'
THOST_FTDC_STS_Finished = '3'
TThostFtdcSettlementStatusType = c_char
TThostFtdcRangeIntTypeType = c_char * 33
TThostFtdcRangeIntFromType = c_char * 33
TThostFtdcRangeIntToType = c_char * 33
TThostFtdcFunctionIDType = c_char * 25
TThostFtdcFunctionValueCodeType = c_char * 257
TThostFtdcFunctionNameType = c_char * 65
TThostFtdcRoleIDType = c_char * 11
TThostFtdcRoleNameType = c_char * 41
TThostFtdcDescriptionType = c_char * 401
TThostFtdcCombineIDType = c_char * 25
TThostFtdcCombineTypeType = c_char * 25
THOST_FTDC_CT_Person = '0'
THOST_FTDC_CT_Company = '1'
THOST_FTDC_CT_Fund = '2'
THOST_FTDC_CT_SpecialOrgan = '3'
THOST_FTDC_CT_Asset = '4'
TThostFtdcInvestorTypeType = c_char
THOST_FTDC_BT_Trade = '0'
THOST_FTDC_BT_TradeSettle = '1'
TThostFtdcBrokerTypeType = c_char
THOST_FTDC_FAS_Low = '1'
THOST_FTDC_FAS_Normal = '2'
THOST_FTDC_FAS_Focus = '3'
THOST_FTDC_FAS_Risk = '4'
TThostFtdcRiskLevelType = c_char
THOST_FTDC_FAS_ByTrade = '1'
THOST_FTDC_FAS_ByDeliv = '2'
THOST_FTDC_FAS_None = '3'
THOST_FTDC_FAS_FixFee = '4'
TThostFtdcFeeAcceptStyleType = c_char
THOST_FTDC_PWDT_Trade = '1'
THOST_FTDC_PWDT_Account = '2'
TThostFtdcPasswordTypeType = c_char
THOST_FTDC_AG_All = '1'
THOST_FTDC_AG_OnlyLost = '2'
THOST_FTDC_AG_OnlyGain = '3'
THOST_FTDC_AG_None = '4'
TThostFtdcAlgorithmType = c_char
THOST_FTDC_ICP_Include = '0'
THOST_FTDC_ICP_NotInclude = '2'
TThostFtdcIncludeCloseProfitType = c_char
THOST_FTDC_AWT_Enable = '0'
THOST_FTDC_AWT_Disable = '2'
THOST_FTDC_AWT_NoHoldEnable = '3'
TThostFtdcAllWithoutTradeType = c_char
TThostFtdcCommentType = c_char * 31
TThostFtdcVersionType = c_char * 4
TThostFtdcTradeCodeType = c_char * 7
TThostFtdcTradeDateType = c_char * 9
TThostFtdcTradeTimeType = c_char * 9
TThostFtdcTradeSerialType = c_char * 9
TThostFtdcTradeSerialNoType = c_int
TThostFtdcFutureIDType = c_char * 11
TThostFtdcBankIDType = c_char * 4
TThostFtdcBankBrchIDType = c_char * 5
TThostFtdcBankBranchIDType = c_char * 11
TThostFtdcOperNoType = c_char * 17
TThostFtdcDeviceIDType = c_char * 3
TThostFtdcRecordNumType = c_char * 7
TThostFtdcFutureAccountType = c_char * 22
THOST_FTDC_FPWD_UnCheck = '0'
THOST_FTDC_FPWD_Check = '1'
TThostFtdcFuturePwdFlagType = c_char
THOST_FTDC_TT_BankToFuture = '0'
THOST_FTDC_TT_FutureToBank = '1'
TThostFtdcTransferTypeType = c_char
TThostFtdcFutureAccPwdType = c_char * 17
TThostFtdcCurrencyCodeType = c_char * 4
TThostFtdcRetCodeType = c_char * 5
TThostFtdcRetInfoType = c_char * 129
TThostFtdcTradeAmtType = c_char * 20
TThostFtdcUseAmtType = c_char * 20
TThostFtdcFetchAmtType = c_char * 20
THOST_FTDC_TVF_Invalid = '0'
THOST_FTDC_TVF_Valid = '1'
THOST_FTDC_TVF_Reverse = '2'
TThostFtdcTransferValidFlagType = c_char
TThostFtdcCertCodeType = c_char * 21
THOST_FTDC_RN_CD = '0'
THOST_FTDC_RN_ZT = '1'
THOST_FTDC_RN_QT = '2'
TThostFtdcReasonType = c_char
TThostFtdcFundProjectIDType = c_char * 5
THOST_FTDC_SEX_None = '0'
THOST_FTDC_SEX_Man = '1'
THOST_FTDC_SEX_Woman = '2'
TThostFtdcSexType = c_char
TThostFtdcProfessionType = c_char * 101
TThostFtdcNationalType = c_char * 31
TThostFtdcProvinceType = c_char * 51
TThostFtdcRegionType = c_char * 16
TThostFtdcCountryType = c_char * 16
TThostFtdcLicenseNOType = c_char * 33
TThostFtdcCompanyTypeType = c_char * 16
TThostFtdcBusinessScopeType = c_char * 1001
TThostFtdcCapitalCurrencyType = c_char * 4
THOST_FTDC_UT_Investor = '0'
THOST_FTDC_UT_Operator = '1'
THOST_FTDC_UT_SuperUser = '2'
TThostFtdcUserTypeType = c_char
THOST_FTDC_RATETYPE_MarginRate = '2'
TThostFtdcRateTypeType = c_char
THOST_FTDC_NOTETYPE_TradeSettleBill = '1'
THOST_FTDC_NOTETYPE_TradeSettleMonth = '2'
THOST_FTDC_NOTETYPE_CallMarginNotes = '3'
THOST_FTDC_NOTETYPE_ForceCloseNotes = '4'
THOST_FTDC_NOTETYPE_TradeNotes = '5'
THOST_FTDC_NOTETYPE_DelivNotes = '6'
TThostFtdcNoteTypeType = c_char
THOST_FTDC_SBS_Day = '1'
THOST_FTDC_SBS_Volume = '2'
TThostFtdcSettlementStyleType = c_char
TThostFtdcBrokerDNSType = c_char * 256
TThostFtdcSentenceType = c_char * 501
THOST_FTDC_ST_Day = '0'
THOST_FTDC_ST_Month = '1'
TThostFtdcSettlementBillTypeType = c_char
THOST_FTDC_URT_Logon = '1'
THOST_FTDC_URT_Transfer = '2'
THOST_FTDC_URT_EMail = '3'
THOST_FTDC_URT_Fax = '4'
THOST_FTDC_URT_ConditionOrder = '5'
TThostFtdcUserRightTypeType = c_char
THOST_FTDC_MPT_PreSettlementPrice = '1'
THOST_FTDC_MPT_SettlementPrice = '2'
THOST_FTDC_MPT_AveragePrice = '3'
THOST_FTDC_MPT_OpenPrice = '4'
TThostFtdcMarginPriceTypeType = c_char
THOST_FTDC_BGS_None = '0'
THOST_FTDC_BGS_NoGenerated = '1'
THOST_FTDC_BGS_Generated = '2'
TThostFtdcBillGenStatusType = c_char
THOST_FTDC_AT_HandlePositionAlgo = '1'
THOST_FTDC_AT_FindMarginRateAlgo = '2'
TThostFtdcAlgoTypeType = c_char
THOST_FTDC_HPA_Base = '1'
THOST_FTDC_HPA_DCE = '2'
THOST_FTDC_HPA_CZCE = '3'
TThostFtdcHandlePositionAlgoIDType = c_char
THOST_FTDC_FMRA_Base = '1'
THOST_FTDC_FMRA_DCE = '2'
THOST_FTDC_FMRA_CZCE = '3'
TThostFtdcFindMarginRateAlgoIDType = c_char
THOST_FTDC_HTAA_Base = '1'
THOST_FTDC_HTAA_DCE = '2'
THOST_FTDC_HTAA_CZCE = '3'
TThostFtdcHandleTradingAccountAlgoIDType = c_char
THOST_FTDC_PST_Order = '1'
THOST_FTDC_PST_Open = '2'
THOST_FTDC_PST_Fund = '3'
THOST_FTDC_PST_Settlement = '4'
THOST_FTDC_PST_Company = '5'
THOST_FTDC_PST_Corporation = '6'
THOST_FTDC_PST_LinkMan = '7'
THOST_FTDC_PST_Ledger = '8'
THOST_FTDC_PST_Trustee = '9'
THOST_FTDC_PST_TrusteeCorporation = 'A'
THOST_FTDC_PST_TrusteeOpen = 'B'
THOST_FTDC_PST_TrusteeContact = 'C'
THOST_FTDC_PST_ForeignerRefer = 'D'
THOST_FTDC_PST_CorporationRefer = 'E'
TThostFtdcPersonTypeType = c_char
THOST_FTDC_QIR_All = '1'
THOST_FTDC_QIR_Group = '2'
THOST_FTDC_QIR_Single = '3'
TThostFtdcQueryInvestorRangeType = c_char
THOST_FTDC_IRS_Normal = '1'
THOST_FTDC_IRS_Warn = '2'
THOST_FTDC_IRS_Call = '3'
THOST_FTDC_IRS_Force = '4'
THOST_FTDC_IRS_Exception = '5'
TThostFtdcInvestorRiskStatusType = c_char
TThostFtdcLegIDType = c_int
TThostFtdcLegMultipleType = c_int
TThostFtdcImplyLevelType = c_int
TThostFtdcClearAccountType = c_char * 33
TThostFtdcOrganNOType = c_char * 6
TThostFtdcClearbarchIDType = c_char * 6
THOST_FTDC_UET_Login = '1'
THOST_FTDC_UET_Logout = '2'
THOST_FTDC_UET_Trading = '3'
THOST_FTDC_UET_TradingError = '4'
THOST_FTDC_UET_UpdatePassword = '5'
THOST_FTDC_UET_Authenticate = '6'
THOST_FTDC_UET_Other = '9'
TThostFtdcUserEventTypeType = c_char
TThostFtdcUserEventInfoType = c_char * 1025
THOST_FTDC_ICS_Close = '0'
THOST_FTDC_ICS_CloseToday = '1'
TThostFtdcCloseStyleType = c_char
THOST_FTDC_SM_Non = '0'
THOST_FTDC_SM_Instrument = '1'
THOST_FTDC_SM_Product = '2'
THOST_FTDC_SM_Investor = '3'
TThostFtdcStatModeType = c_char
THOST_FTDC_PAOS_NotSend = '1'
THOST_FTDC_PAOS_Send = '2'
THOST_FTDC_PAOS_Deleted = '3'
TThostFtdcParkedOrderStatusType = c_char
TThostFtdcParkedOrderIDType = c_char * 13
TThostFtdcParkedOrderActionIDType = c_char * 13
THOST_FTDC_VDS_Dealing = '1'
THOST_FTDC_VDS_DeaclSucceed = '2'
TThostFtdcVirDealStatusType = c_char
THOST_FTDC_ORGS_Standard = '0'
THOST_FTDC_ORGS_ESunny = '1'
THOST_FTDC_ORGS_KingStarV6 = '2'
TThostFtdcOrgSystemIDType = c_char
THOST_FTDC_VTS_NaturalDeal = '0'
THOST_FTDC_VTS_SucceedEnd = '1'
THOST_FTDC_VTS_FailedEND = '2'
THOST_FTDC_VTS_Exception = '3'
THOST_FTDC_VTS_ManualDeal = '4'
THOST_FTDC_VTS_MesException = '5'
THOST_FTDC_VTS_SysException = '6'
TThostFtdcVirTradeStatusType = c_char
THOST_FTDC_VBAT_BankBook = '1'
THOST_FTDC_VBAT_BankCard = '2'
THOST_FTDC_VBAT_CreditCard = '3'
TThostFtdcVirBankAccTypeType = c_char
THOST_FTDC_VMS_Natural = '0'
THOST_FTDC_VMS_Canceled = '9'
TThostFtdcVirementStatusType = c_char
THOST_FTDC_VAA_NoAvailAbility = '0'
THOST_FTDC_VAA_AvailAbility = '1'
THOST_FTDC_VAA_Repeal = '2'
TThostFtdcVirementAvailAbilityType = c_char
THOST_FTDC_VTC_BankBankToFuture = '102001'
THOST_FTDC_VTC_BankFutureToBank = '102002'
THOST_FTDC_VTC_FutureBankToFuture = '202001'
THOST_FTDC_VTC_FutureFutureToBank = '202002'
TThostFtdcVirementTradeCodeType = c_char
TThostFtdcPhotoTypeNameType = c_char * 41
TThostFtdcPhotoTypeIDType = c_char * 5
TThostFtdcPhotoNameType = c_char * 161
TThostFtdcTopicIDType = c_int
TThostFtdcReportTypeIDType = c_char * 3
TThostFtdcCharacterIDType = c_char * 5
TThostFtdcAMLParamIDType = c_char * 21
TThostFtdcAMLInvestorTypeType = c_char * 3
TThostFtdcAMLIdCardTypeType = c_char * 3
TThostFtdcAMLTradeDirectType = c_char * 3
TThostFtdcAMLTradeModelType = c_char * 3
TThostFtdcAMLParamIDType = c_char * 21
TThostFtdcAMLOpParamValueType = c_double
TThostFtdcAMLCustomerCardTypeType = c_char * 81
TThostFtdcAMLInstitutionNameType = c_char * 65
TThostFtdcAMLDistrictIDType = c_char * 7
TThostFtdcAMLRelationShipType = c_char * 3
TThostFtdcAMLInstitutionTypeType = c_char * 3
TThostFtdcAMLInstitutionIDType = c_char * 13
TThostFtdcAMLAccountTypeType = c_char * 5
TThostFtdcAMLTradingTypeType = c_char * 7
TThostFtdcAMLTransactClassType = c_char * 7
TThostFtdcAMLCapitalIOType = c_char * 3
TThostFtdcAMLSiteType = c_char * 10
TThostFtdcAMLCapitalPurposeType = c_char * 129
TThostFtdcAMLReportTypeType = c_char * 2
TThostFtdcAMLSerialNoType = c_char * 5
TThostFtdcAMLStatusType = c_char * 2
THOST_FTDC_GEN_Program = '0'
THOST_FTDC_GEN_HandWork = '1'
TThostFtdcAMLGenStatusType = c_char
TThostFtdcAMLSeqCodeType = c_char * 65
TThostFtdcAMLFileNameType = c_char * 257
TThostFtdcAMLMoneyType = c_double
TThostFtdcAMLFileAmountType = c_int
TThostFtdcCFMMCKeyType = c_char * 21
TThostFtdcCFMMCTokenType = c_char * 21
THOST_FTDC_CFMMCKK_REQUEST = 'R'
THOST_FTDC_CFMMCKK_AUTO = 'A'
THOST_FTDC_CFMMCKK_MANUAL = 'M'
TThostFtdcCFMMCKeyKindType = c_char
TThostFtdcAMLReportNameType = c_char * 81
TThostFtdcIndividualNameType = c_char * 51
TThostFtdcCurrencyIDType = c_char * 4
TThostFtdcCustNumberType = c_char * 36
TThostFtdcOrganCodeType = c_char * 36
TThostFtdcOrganNameType = c_char * 71
TThostFtdcSuperOrganCodeType = c_char * 12
TThostFtdcSubBranchIDType = c_char * 31
TThostFtdcSubBranchNameType = c_char * 71
TThostFtdcBranchNetCodeType = c_char * 31
TThostFtdcBranchNetNameType = c_char * 71
TThostFtdcOrganFlagType = c_char * 2
TThostFtdcBankCodingForFutureType = c_char * 33
TThostFtdcBankReturnCodeType = c_char * 7
TThostFtdcPlateReturnCodeType = c_char * 5
TThostFtdcBankSubBranchIDType = c_char * 31
TThostFtdcFutureBranchIDType = c_char * 31
TThostFtdcReturnCodeType = c_char * 7
TThostFtdcOperatorCodeType = c_char * 17
TThostFtdcClearDepIDType = c_char * 6
TThostFtdcClearBrchIDType = c_char * 6
TThostFtdcClearNameType = c_char * 71
TThostFtdcBankAccountNameType = c_char * 71
TThostFtdcInvDepIDType = c_char * 6
TThostFtdcInvBrchIDType = c_char * 6
TThostFtdcMessageFormatVersionType = c_char * 36
TThostFtdcDigestType = c_char * 36
TThostFtdcAuthenticDataType = c_char * 129
TThostFtdcPasswordKeyType = c_char * 129
TThostFtdcFutureAccountNameType = c_char * 129
TThostFtdcMobilePhoneType = c_char * 21
TThostFtdcFutureMainKeyType = c_char * 129
TThostFtdcFutureWorkKeyType = c_char * 129
TThostFtdcFutureTransKeyType = c_char * 129
TThostFtdcBankMainKeyType = c_char * 129
TThostFtdcBankWorkKeyType = c_char * 129
TThostFtdcBankTransKeyType = c_char * 129
TThostFtdcBankServerDescriptionType = c_char * 129
TThostFtdcAddInfoType = c_char * 129
TThostFtdcDescrInfoForReturnCodeType = c_char * 129
TThostFtdcCountryCodeType = c_char * 21
TThostFtdcSerialType = c_int
TThostFtdcPlateSerialType = c_int
TThostFtdcBankSerialType = c_char * 13
TThostFtdcCorrectSerialType = c_int
TThostFtdcFutureSerialType = c_int
TThostFtdcApplicationIDType = c_int
TThostFtdcBankProxyIDType = c_int
TThostFtdcFBTCoreIDType = c_int
TThostFtdcServerPortType = c_int
TThostFtdcRepealedTimesType = c_int
TThostFtdcRepealTimeIntervalType = c_int
TThostFtdcTotalTimesType = c_int
TThostFtdcFBTRequestIDType = c_int
TThostFtdcTIDType = c_int
TThostFtdcTradeAmountType = c_double
TThostFtdcCustFeeType = c_double
TThostFtdcFutureFeeType = c_double
TThostFtdcSingleMaxAmtType = c_double
TThostFtdcSingleMinAmtType = c_double
TThostFtdcTotalAmtType = c_double
THOST_FTDC_CFT_IDCard = '0'
THOST_FTDC_CFT_Passport = '1'
THOST_FTDC_CFT_OfficerIDCard = '2'
THOST_FTDC_CFT_SoldierIDCard = '3'
THOST_FTDC_CFT_HomeComingCard = '4'
THOST_FTDC_CFT_HouseholdRegister = '5'
THOST_FTDC_CFT_LicenseNo = '6'
THOST_FTDC_CFT_InstitutionCodeCard = '7'
THOST_FTDC_CFT_TempLicenseNo = '8'
THOST_FTDC_CFT_NoEnterpriseLicenseNo = '9'
THOST_FTDC_CFT_OtherCard = 'x'
THOST_FTDC_CFT_SuperDepAgree = 'a'
TThostFtdcCertificationTypeType = c_char
THOST_FTDC_FBC_Others = '0'
THOST_FTDC_FBC_TransferDetails = '1'
THOST_FTDC_FBC_CustAccStatus = '2'
THOST_FTDC_FBC_AccountTradeDetails = '3'
THOST_FTDC_FBC_FutureAccountChangeInfoDetails = '4'
THOST_FTDC_FBC_CustMoneyDetail = '5'
THOST_FTDC_FBC_CustCancelAccountInfo = '6'
THOST_FTDC_FBC_CustMoneyResult = '7'
THOST_FTDC_FBC_OthersExceptionResult = '8'
THOST_FTDC_FBC_CustInterestNetMoneyDetails = '9'
THOST_FTDC_FBC_CustMoneySendAndReceiveDetails = 'a'
THOST_FTDC_FBC_CorporationMoneyTotal = 'b'
THOST_FTDC_FBC_MainbodyMoneyTotal = 'c'
THOST_FTDC_FBC_MainPartMonitorData = 'd'
THOST_FTDC_FBC_PreparationMoney = 'e'
THOST_FTDC_FBC_BankMoneyMonitorData = 'f'
TThostFtdcFileBusinessCodeType = c_char
THOST_FTDC_CEC_Exchange = '1'
THOST_FTDC_CEC_Cash = '2'
TThostFtdcCashExchangeCodeType = c_char
THOST_FTDC_YNI_Yes = '0'
THOST_FTDC_YNI_No = '1'
TThostFtdcYesNoIndicatorType = c_char
THOST_FTDC_BLT_CurrentMoney = '0'
THOST_FTDC_BLT_UsableMoney = '1'
THOST_FTDC_BLT_FetchableMoney = '2'
THOST_FTDC_BLT_FreezeMoney = '3'
TThostFtdcBanlanceTypeType = c_char
THOST_FTDC_GD_Unknown = '0'
THOST_FTDC_GD_Male = '1'
THOST_FTDC_GD_Female = '2'
TThostFtdcGenderType = c_char
THOST_FTDC_FPF_BEN = '0'
THOST_FTDC_FPF_OUR = '1'
THOST_FTDC_FPF_SHA = '2'
TThostFtdcFeePayFlagType = c_char
THOST_FTDC_PWKT_ExchangeKey = '0'
THOST_FTDC_PWKT_PassWordKey = '1'
THOST_FTDC_PWKT_MACKey = '2'
THOST_FTDC_PWKT_MessageKey = '3'
TThostFtdcPassWordKeyTypeType = c_char
THOST_FTDC_PWT_Query = '0'
THOST_FTDC_PWT_Fetch = '1'
THOST_FTDC_PWT_Transfer = '2'
THOST_FTDC_PWT_Trade = '3'
TThostFtdcFBTPassWordTypeType = c_char
THOST_FTDC_EM_NoEncry = '0'
THOST_FTDC_EM_DES = '1'
THOST_FTDC_EM_3DES = '2'
TThostFtdcFBTEncryModeType = c_char
THOST_FTDC_BRF_BankNotNeedRepeal = '0'
THOST_FTDC_BRF_BankWaitingRepeal = '1'
THOST_FTDC_BRF_BankBeenRepealed = '2'
TThostFtdcBankRepealFlagType = c_char
THOST_FTDC_BRORF_BrokerNotNeedRepeal = '0'
THOST_FTDC_BRORF_BrokerWaitingRepeal = '1'
THOST_FTDC_BRORF_BrokerBeenRepealed = '2'
TThostFtdcBrokerRepealFlagType = c_char
THOST_FTDC_TS_Bank = '0'
THOST_FTDC_TS_Future = '1'
THOST_FTDC_TS_Store = '2'
TThostFtdcInstitutionTypeType = c_char
THOST_FTDC_LF_Yes = '0'
THOST_FTDC_LF_No = '1'
TThostFtdcLastFragmentType = c_char
THOST_FTDC_BAS_Normal = '0'
THOST_FTDC_BAS_Freeze = '1'
THOST_FTDC_BAS_ReportLoss = '2'
TThostFtdcBankAccStatusType = c_char
THOST_FTDC_MAS_Normal = '0'
THOST_FTDC_MAS_Cancel = '1'
TThostFtdcMoneyAccountStatusType = c_char
THOST_FTDC_MSS_Point = '0'
THOST_FTDC_MSS_PrePoint = '1'
THOST_FTDC_MSS_CancelPoint = '2'
TThostFtdcManageStatusType = c_char
THOST_FTDC_SYT_FutureBankTransfer = '0'
THOST_FTDC_SYT_StockBankTransfer = '1'
THOST_FTDC_SYT_TheThirdPartStore = '2'
TThostFtdcSystemTypeType = c_char
THOST_FTDC_TEF_NormalProcessing = '0'
THOST_FTDC_TEF_Success = '1'
THOST_FTDC_TEF_Failed = '2'
THOST_FTDC_TEF_Abnormal = '3'
THOST_FTDC_TEF_ManualProcessedForException = '4'
THOST_FTDC_TEF_CommuFailedNeedManualProcess = '5'
THOST_FTDC_TEF_SysErrorNeedManualProcess = '6'
TThostFtdcTxnEndFlagType = c_char
THOST_FTDC_PSS_NotProcess = '0'
THOST_FTDC_PSS_StartProcess = '1'
THOST_FTDC_PSS_Finished = '2'
TThostFtdcProcessStatusType = c_char
THOST_FTDC_CUSTT_Person = '0'
THOST_FTDC_CUSTT_Institution = '1'
TThostFtdcCustTypeType = c_char
THOST_FTDC_FBTTD_FromBankToFuture = '1'
THOST_FTDC_FBTTD_FromFutureToBank = '2'
TThostFtdcFBTTransferDirectionType = c_char
THOST_FTDC_OOD_Open = '1'
THOST_FTDC_OOD_Destroy = '0'
TThostFtdcOpenOrDestroyType = c_char
THOST_FTDC_AVAF_Invalid = '0'
THOST_FTDC_AVAF_Valid = '1'
THOST_FTDC_AVAF_Repeal = '2'
TThostFtdcAvailabilityFlagType = c_char
THOST_FTDC_OT_Bank = '1'
THOST_FTDC_OT_Future = '2'
THOST_FTDC_OT_PlateForm = '9'
TThostFtdcOrganTypeType = c_char
THOST_FTDC_OL_HeadQuarters = '1'
THOST_FTDC_OL_Branch = '2'
TThostFtdcOrganLevelType = c_char
THOST_FTDC_PID_FutureProtocal = '0'
THOST_FTDC_PID_ICBCProtocal = '1'
THOST_FTDC_PID_ABCProtocal = '2'
THOST_FTDC_PID_CBCProtocal = '3'
THOST_FTDC_PID_CCBProtocal = '4'
THOST_FTDC_PID_BOCOMProtocal = '5'
THOST_FTDC_PID_FBTPlateFormProtocal = 'X'
TThostFtdcProtocalIDType = c_char
THOST_FTDC_CM_ShortConnect = '0'
THOST_FTDC_CM_LongConnect = '1'
TThostFtdcConnectModeType = c_char
THOST_FTDC_SRM_ASync = '0'
THOST_FTDC_SRM_Sync = '1'
TThostFtdcSyncModeType = c_char
THOST_FTDC_BAT_BankBook = '1'
THOST_FTDC_BAT_SavingCard = '2'
THOST_FTDC_BAT_CreditCard = '3'
TThostFtdcBankAccTypeType = c_char
THOST_FTDC_FAT_BankBook = '1'
THOST_FTDC_FAT_SavingCard = '2'
THOST_FTDC_FAT_CreditCard = '3'
TThostFtdcFutureAccTypeType = c_char
THOST_FTDC_OS_Ready = '0'
THOST_FTDC_OS_CheckIn = '1'
THOST_FTDC_OS_CheckOut = '2'
THOST_FTDC_OS_CheckFileArrived = '3'
THOST_FTDC_OS_CheckDetail = '4'
THOST_FTDC_OS_DayEndClean = '5'
THOST_FTDC_OS_Invalid = '9'
TThostFtdcOrganStatusType = c_char
THOST_FTDC_CCBFM_ByAmount = '1'
THOST_FTDC_CCBFM_ByMonth = '2'
TThostFtdcCCBFeeModeType = c_char
THOST_FTDC_CAPIT_Client = '1'
THOST_FTDC_CAPIT_Server = '2'
THOST_FTDC_CAPIT_UserApi = '3'
TThostFtdcCommApiTypeType = c_char
TThostFtdcServiceIDType = c_int
TThostFtdcServiceLineNoType = c_int
TThostFtdcServiceNameType = c_char * 61
THOST_FTDC_LS_Connected = '1'
THOST_FTDC_LS_Disconnected = '2'
TThostFtdcLinkStatusType = c_char
TThostFtdcCommApiPointerType = c_int
THOST_FTDC_BPWDF_NoCheck = '0'
THOST_FTDC_BPWDF_BlankCheck = '1'
THOST_FTDC_BPWDF_EncryptCheck = '2'
TThostFtdcPwdFlagType = c_char
THOST_FTDC_SAT_AccountID = '1'
THOST_FTDC_SAT_CardID = '2'
THOST_FTDC_SAT_SHStockholderID = '3'
THOST_FTDC_SAT_SZStockholderID = '4'
TThostFtdcSecuAccTypeType = c_char
THOST_FTDC_TRFS_Normal = '0'
THOST_FTDC_TRFS_Repealed = '1'
TThostFtdcTransferStatusType = c_char
THOST_FTDC_SPTYPE_Broker = '0'
THOST_FTDC_SPTYPE_Bank = '1'
TThostFtdcSponsorTypeType = c_char
THOST_FTDC_REQRSP_Request = '0'
THOST_FTDC_REQRSP_Response = '1'
TThostFtdcReqRspTypeType = c_char
THOST_FTDC_FBTUET_SignIn = '0'
THOST_FTDC_FBTUET_FromBankToFuture = '1'
THOST_FTDC_FBTUET_FromFutureToBank = '2'
THOST_FTDC_FBTUET_OpenAccount = '3'
THOST_FTDC_FBTUET_CancelAccount = '4'
THOST_FTDC_FBTUET_ChangeAccount = '5'
THOST_FTDC_FBTUET_RepealFromBankToFuture = '6'
THOST_FTDC_FBTUET_RepealFromFutureToBank = '7'
THOST_FTDC_FBTUET_QueryBankAccount = '8'
THOST_FTDC_FBTUET_QueryFutureAccount = '9'
THOST_FTDC_FBTUET_SignOut = 'A'
THOST_FTDC_FBTUET_SyncKey = 'B'
THOST_FTDC_FBTUET_Other = 'Z'
TThostFtdcFBTUserEventTypeType = c_char
TThostFtdcBankIDByBankType = c_char * 21
TThostFtdcBankOperNoType = c_char * 4
TThostFtdcBankCustNoType = c_char * 21
TThostFtdcDBOPSeqNoType = c_int
TThostFtdcTableNameType = c_char * 61
TThostFtdcPKNameType = c_char * 201
TThostFtdcPKValueType = c_char * 501
THOST_FTDC_DBOP_Insert = '0'
THOST_FTDC_DBOP_Update = '1'
THOST_FTDC_DBOP_Delete = '2'
TThostFtdcDBOperationType = c_char
THOST_FTDC_SYNF_Yes = '0'
THOST_FTDC_SYNF_No = '1'
TThostFtdcSyncFlagType = c_char
TThostFtdcTargetIDType = c_char * 4
THOST_FTDC_SYNT_OneOffSync = '0'
THOST_FTDC_SYNT_TimerSync = '1'
THOST_FTDC_SYNT_TimerFullSync = '2'
TThostFtdcSyncTypeType = c_char
TThostFtdcFBETimeType = c_char * 7
TThostFtdcFBEBankNoType = c_char * 13
TThostFtdcFBECertNoType = c_char * 13
THOST_FTDC_FBEDIR_Settlement = '0'
THOST_FTDC_FBEDIR_Sale = '1'
TThostFtdcExDirectionType = c_char
TThostFtdcFBEBankAccountType = c_char * 33
TThostFtdcFBEBankAccountNameType = c_char * 61
TThostFtdcFBEAmtType = c_double
TThostFtdcFBEBusinessTypeType = c_char * 3
TThostFtdcFBEPostScriptType = c_char * 61
TThostFtdcFBERemarkType = c_char * 71
TThostFtdcExRateType = c_double
THOST_FTDC_FBERES_Success = '0'
THOST_FTDC_FBERES_InsufficientBalance = '1'
THOST_FTDC_FBERES_UnknownTrading = '8'
THOST_FTDC_FBERES_Fail = 'x'
TThostFtdcFBEResultFlagType = c_char
TThostFtdcFBERtnMsgType = c_char * 61
TThostFtdcFBEExtendMsgType = c_char * 61
TThostFtdcFBEBusinessSerialType = c_char * 31
TThostFtdcFBESystemSerialType = c_char * 21
TThostFtdcFBETotalExCntType = c_int
THOST_FTDC_FBEES_Normal = '0'
THOST_FTDC_FBEES_ReExchange = '1'
TThostFtdcFBEExchStatusType = c_char
THOST_FTDC_FBEFG_DataPackage = '0'
THOST_FTDC_FBEFG_File = '1'
TThostFtdcFBEFileFlagType = c_char
THOST_FTDC_FBEAT_NotTrade = '0'
THOST_FTDC_FBEAT_Trade = '1'
TThostFtdcFBEAlreadyTradeType = c_char
TThostFtdcFBEOpenBankType = c_char * 61
THOST_FTDC_FBEUET_SignIn = '0'
THOST_FTDC_FBEUET_Exchange = '1'
THOST_FTDC_FBEUET_ReExchange = '2'
THOST_FTDC_FBEUET_QueryBankAccount = '3'
THOST_FTDC_FBEUET_QueryExchDetial = '4'
THOST_FTDC_FBEUET_QueryExchSummary = '5'
THOST_FTDC_FBEUET_QueryExchRate = '6'
THOST_FTDC_FBEUET_CheckBankAccount = '7'
THOST_FTDC_FBEUET_SignOut = '8'
THOST_FTDC_FBEUET_Other = 'Z'
TThostFtdcFBEUserEventTypeType = c_char
TThostFtdcFBEFileNameType = c_char * 21
TThostFtdcFBEBatchSerialType = c_char * 21
THOST_FTDC_FBERF_UnProcessed = '0'
THOST_FTDC_FBERF_WaitSend = '1'
THOST_FTDC_FBERF_SendSuccess = '2'
THOST_FTDC_FBERF_SendFailed = '3'
THOST_FTDC_FBERF_WaitReSend = '4'
TThostFtdcFBEReqFlagType = c_char
THOST_FTDC_NC_NOERROR = '0'
THOST_FTDC_NC_Warn = '1'
THOST_FTDC_NC_Call = '2'
THOST_FTDC_NC_Force = '3'
THOST_FTDC_NC_CHUANCANG = '4'
THOST_FTDC_NC_Exception = '5'
TThostFtdcNotifyClassType = c_char
TThostFtdcRiskNofityInfoType = c_char * 257
TThostFtdcForceCloseSceneIdType = c_char * 24
THOST_FTDC_FCT_Manual = '0'
THOST_FTDC_FCT_Single = '1'
THOST_FTDC_FCT_Group = '2'
TThostFtdcForceCloseTypeType = c_char
TThostFtdcInstrumentIDsType = c_char * 101
THOST_FTDC_RNM_System = '0'
THOST_FTDC_RNM_SMS = '1'
THOST_FTDC_RNM_EMail = '2'
THOST_FTDC_RNM_Manual = '3'
TThostFtdcRiskNotifyMethodType = c_char
THOST_FTDC_RNS_NotGen = '0'
THOST_FTDC_RNS_Generated = '1'
THOST_FTDC_RNS_SendError = '2'
THOST_FTDC_RNS_SendOk = '3'
THOST_FTDC_RNS_Received = '4'
THOST_FTDC_RNS_Confirmed = '5'
TThostFtdcRiskNotifyStatusType = c_char
THOST_FTDC_RUE_ExportData = '0'
TThostFtdcRiskUserEventType = c_char
TThostFtdcParamIDType = c_int
TThostFtdcParamNameType = c_char * 41
TThostFtdcParamValueType = c_char * 41
THOST_FTDC_COST_LastPriceAsc = '0'
THOST_FTDC_COST_LastPriceDesc = '1'
THOST_FTDC_COST_AskPriceAsc = '2'
THOST_FTDC_COST_AskPriceDesc = '3'
THOST_FTDC_COST_BidPriceAsc = '4'
THOST_FTDC_COST_BidPriceDesc = '5'
TThostFtdcConditionalOrderSortTypeType = c_char
THOST_FTDC_UOAST_NoSend = '0'
THOST_FTDC_UOAST_Sended = '1'
THOST_FTDC_UOAST_Generated = '2'
THOST_FTDC_UOAST_SendFail = '3'
THOST_FTDC_UOAST_Success = '4'
THOST_FTDC_UOAST_Fail = '5'
THOST_FTDC_UOAST_Cancel = '6'
TThostFtdcSendTypeType = c_char
THOST_FTDC_UOACS_NoApply = '1'
THOST_FTDC_UOACS_Submited = '2'
THOST_FTDC_UOACS_Sended = '3'
THOST_FTDC_UOACS_Success = '4'
THOST_FTDC_UOACS_Refuse = '5'
THOST_FTDC_UOACS_Cancel = '6'
TThostFtdcClientIDStatusType = c_char
TThostFtdcIndustryIDType = c_char * 17
TThostFtdcQuestionIDType = c_char * 5
TThostFtdcQuestionContentType = c_char * 41
TThostFtdcOptionIDType = c_char * 13
TThostFtdcOptionContentType = c_char * 61
THOST_FTDC_QT_Radio = '1'
THOST_FTDC_QT_Option = '2'
THOST_FTDC_QT_Blank = '3'
TThostFtdcQuestionTypeType = c_char
TThostFtdcProcessIDType = c_char * 33
TThostFtdcSeqNoType = c_int
TThostFtdcUOAProcessStatusType = c_char * 3
TThostFtdcProcessTypeType = c_char * 3
THOST_FTDC_BT_Request = '1'
THOST_FTDC_BT_Response = '2'
THOST_FTDC_BT_Notice = '3'
TThostFtdcBusinessTypeType = c_char
THOST_FTDC_CRC_Success = '0'
THOST_FTDC_CRC_Working = '1'
THOST_FTDC_CRC_InfoFail = '2'
THOST_FTDC_CRC_IDCardFail = '3'
THOST_FTDC_CRC_OtherFail = '4'
TThostFtdcCfmmcReturnCodeType = c_char
TThostFtdcExReturnCodeType = c_int
THOST_FTDC_CfMMCCT_All = '0'
THOST_FTDC_CfMMCCT_Person = '1'
THOST_FTDC_CfMMCCT_Company = '2'
THOST_FTDC_CfMMCCT_Other = '3'
THOST_FTDC_CfMMCCT_SpecialOrgan = '4'
THOST_FTDC_CfMMCCT_Asset = '5'
TThostFtdcClientTypeType = c_char
THOST_FTDC_EIDT_SHFE = 'S'
THOST_FTDC_EIDT_CZCE = 'Z'
THOST_FTDC_EIDT_DCE = 'D'
THOST_FTDC_EIDT_CFFEX = 'J'
THOST_FTDC_EIDT_INE = 'N'
TThostFtdcExchangeIDTypeType = c_char
THOST_FTDC_ECIDT_Hedge = '1'
THOST_FTDC_ECIDT_Arbitrage = '2'
THOST_FTDC_ECIDT_Speculation = '3'
TThostFtdcExClientIDTypeType = c_char
TThostFtdcClientClassifyType = c_char * 11
TThostFtdcUOAOrganTypeType = c_char * 11
TThostFtdcUOACountryCodeType = c_char * 11
TThostFtdcAreaCodeType = c_char * 11
TThostFtdcFuturesIDType = c_char * 21
TThostFtdcCffmcDateType = c_char * 11
TThostFtdcCffmcTimeType = c_char * 11
TThostFtdcNocIDType = c_char * 21
THOST_FTDC_UF_NoUpdate = '0'
THOST_FTDC_UF_Success = '1'
THOST_FTDC_UF_Fail = '2'
THOST_FTDC_UF_TCSuccess = '3'
THOST_FTDC_UF_TCFail = '4'
THOST_FTDC_UF_Cancel = '5'
TThostFtdcUpdateFlagType = c_char
THOST_FTDC_AOID_OpenInvestor = '1'
THOST_FTDC_AOID_ModifyIDCard = '2'
THOST_FTDC_AOID_ModifyNoIDCard = '3'
THOST_FTDC_AOID_ApplyTradingCode = '4'
THOST_FTDC_AOID_CancelTradingCode = '5'
THOST_FTDC_AOID_CancelInvestor = '6'
THOST_FTDC_AOID_FreezeAccount = '8'
THOST_FTDC_AOID_ActiveFreezeAccount = '9'
TThostFtdcApplyOperateIDType = c_char
THOST_FTDC_ASID_NoComplete = '1'
THOST_FTDC_ASID_Submited = '2'
THOST_FTDC_ASID_Checked = '3'
THOST_FTDC_ASID_Refused = '4'
THOST_FTDC_ASID_Deleted = '5'
TThostFtdcApplyStatusIDType = c_char
THOST_FTDC_UOASM_ByAPI = '1'
THOST_FTDC_UOASM_ByFile = '2'
TThostFtdcSendMethodType = c_char
TThostFtdcEventTypeType = c_char * 33
THOST_FTDC_EvM_ADD = '1'
THOST_FTDC_EvM_UPDATE = '2'
THOST_FTDC_EvM_DELETE = '3'
THOST_FTDC_EvM_CHECK = '4'
THOST_FTDC_EvM_COPY = '5'
THOST_FTDC_EvM_CANCEL = '6'
THOST_FTDC_EvM_Reverse = '7'
TThostFtdcEventModeType = c_char
THOST_FTDC_UOAA_ASR = '1'
THOST_FTDC_UOAA_ASNR = '2'
THOST_FTDC_UOAA_NSAR = '3'
THOST_FTDC_UOAA_NSR = '4'
TThostFtdcUOAAutoSendType = c_char
TThostFtdcQueryDepthType = c_int
TThostFtdcDataCenterIDType = c_int
THOST_FTDC_EvM_InvestorGroupFlow = '1'
THOST_FTDC_EvM_InvestorRate = '2'
THOST_FTDC_EvM_InvestorCommRateModel = '3'
TThostFtdcFlowIDType = c_char
THOST_FTDC_CL_Zero = '0'
THOST_FTDC_CL_One = '1'
THOST_FTDC_CL_Two = '2'
TThostFtdcCheckLevelType = c_char
TThostFtdcCheckNoType = c_int
THOST_FTDC_CHS_Init = '0'
THOST_FTDC_CHS_Checking = '1'
THOST_FTDC_CHS_Checked = '2'
THOST_FTDC_CHS_Refuse = '3'
THOST_FTDC_CHS_Cancel = '4'
TThostFtdcCheckStatusType = c_char
THOST_FTDC_CHU_Unused = '0'
THOST_FTDC_CHU_Used = '1'
THOST_FTDC_CHU_Fail = '2'
TThostFtdcUsedStatusType = c_char
TThostFtdcRateTemplateNameType = c_char * 61
TThostFtdcPropertyStringType = c_char * 2049
THOST_FTDC_BAO_ByAccProperty = '0'
THOST_FTDC_BAO_ByFBTransfer = '1'
TThostFtdcBankAcountOriginType = c_char
THOST_FTDC_MBTS_ByInstrument = '0'
THOST_FTDC_MBTS_ByDayInsPrc = '1'
THOST_FTDC_MBTS_ByDayIns = '2'
TThostFtdcMonthBillTradeSumType = c_char
THOST_FTDC_FTC_BankLaunchBankToBroker = '102001'
THOST_FTDC_FTC_BrokerLaunchBankToBroker = '202001'
THOST_FTDC_FTC_BankLaunchBrokerToBank = '102002'
THOST_FTDC_FTC_BrokerLaunchBrokerToBank = '202002'
TThostFtdcFBTTradeCodeEnumType = c_char
TThostFtdcRateTemplateIDType = c_char * 9
TThostFtdcRiskRateType = c_char * 21
TThostFtdcTimestampType = c_int
TThostFtdcInvestorIDRuleNameType = c_char * 61
TThostFtdcInvestorIDRuleExprType = c_char * 513
TThostFtdcLastDriftType = c_int
TThostFtdcLastSuccessType = c_int
TThostFtdcAuthKeyType = c_char * 41
TThostFtdcSerialNumberType = c_char * 17
THOST_FTDC_OTP_NONE = '0'
THOST_FTDC_OTP_TOTP = '1'
TThostFtdcOTPTypeType = c_char
TThostFtdcOTPVendorsIDType = c_char * 2
TThostFtdcOTPVendorsNameType = c_char * 61
THOST_FTDC_OTPS_Unused = '0'
THOST_FTDC_OTPS_Used = '1'
THOST_FTDC_OTPS_Disuse = '2'
TThostFtdcOTPStatusType = c_char
THOST_FTDC_BUT_Investor = '1'
THOST_FTDC_BUT_BrokerUser = '2'
TThostFtdcBrokerUserTypeType = c_char
THOST_FTDC_FUTT_Commodity = '1'
THOST_FTDC_FUTT_Financial = '2'
TThostFtdcFutureTypeType = c_char
THOST_FTDC_FET_Restriction = '0'
THOST_FTDC_FET_TodayRestriction = '1'
THOST_FTDC_FET_Transfer = '2'
THOST_FTDC_FET_Credit = '3'
THOST_FTDC_FET_InvestorWithdrawAlm = '4'
THOST_FTDC_FET_BankRestriction = '5'
THOST_FTDC_FET_Accountregister = '6'
THOST_FTDC_FET_ExchangeFundIO = '7'
THOST_FTDC_FET_InvestorFundIO = '8'
TThostFtdcFundEventTypeType = c_char
THOST_FTDC_AST_FBTransfer = '0'
THOST_FTDC_AST_ManualEntry = '1'
TThostFtdcAccountSourceTypeType = c_char
THOST_FTDC_CST_UnifyAccount = '0'
THOST_FTDC_CST_ManualEntry = '1'
TThostFtdcCodeSourceTypeType = c_char
THOST_FTDC_UR_All = '0'
THOST_FTDC_UR_Single = '1'
TThostFtdcUserRangeType = c_char
TThostFtdcTimeSpanType = c_char * 9
TThostFtdcImportSequenceIDType = c_char * 17
THOST_FTDC_BG_Investor = '2'
THOST_FTDC_BG_Group = '1'
TThostFtdcByGroupType = c_char
THOST_FTDC_TSSM_Instrument = '1'
THOST_FTDC_TSSM_Product = '2'
THOST_FTDC_TSSM_Exchange = '3'
TThostFtdcTradeSumStatModeType = c_char
TThostFtdcComTypeType = c_int
TThostFtdcUserProductIDType = c_char * 33
TThostFtdcUserProductNameType = c_char * 65
TThostFtdcUserProductMemoType = c_char * 129
TThostFtdcCSRCCancelFlagType = c_char * 2
TThostFtdcCSRCDateType = c_char * 11
TThostFtdcCSRCInvestorNameType = c_char * 201
TThostFtdcCSRCOpenInvestorNameType = c_char * 101
TThostFtdcCSRCInvestorIDType = c_char * 13
TThostFtdcCSRCIdentifiedCardNoType = c_char * 51
TThostFtdcCSRCClientIDType = c_char * 11
TThostFtdcCSRCBankFlagType = c_char * 3
TThostFtdcCSRCBankAccountType = c_char * 23
TThostFtdcCSRCOpenNameType = c_char * 401
TThostFtdcCSRCMemoType = c_char * 101
TThostFtdcCSRCTimeType = c_char * 11
TThostFtdcCSRCTradeIDType = c_char * 21
TThostFtdcCSRCExchangeInstIDType = c_char * 31
TThostFtdcCSRCMortgageNameType = c_char * 7
TThostFtdcCSRCReasonType = c_char * 3
TThostFtdcIsSettlementType = c_char * 2
TThostFtdcCSRCMoneyType = c_double
TThostFtdcCSRCPriceType = c_double
TThostFtdcCSRCOptionsTypeType = c_char * 2
TThostFtdcCSRCStrikePriceType = c_double
TThostFtdcCSRCTargetProductIDType = c_char * 3
TThostFtdcCSRCTargetInstrIDType = c_char * 31
TThostFtdcCommModelNameType = c_char * 161
TThostFtdcCommModelMemoType = c_char * 1025
THOST_FTDC_ESM_Relative = '1'
THOST_FTDC_ESM_Typical = '2'
TThostFtdcExprSetModeType = c_char
THOST_FTDC_RIR_All = '1'
THOST_FTDC_RIR_Model = '2'
THOST_FTDC_RIR_Single = '3'
TThostFtdcRateInvestorRangeType = c_char
TThostFtdcAgentBrokerIDType = c_char * 13
TThostFtdcDRIdentityIDType = c_int
TThostFtdcDRIdentityNameType = c_char * 65
TThostFtdcDBLinkIDType = c_char * 31
THOST_FTDC_SDS_Initialize = '0'
THOST_FTDC_SDS_Settlementing = '1'
THOST_FTDC_SDS_Settlemented = '2'
TThostFtdcSyncDataStatusType = c_char
THOST_FTDC_TSRC_NORMAL = '0'
THOST_FTDC_TSRC_QUERY = '1'
TThostFtdcTradeSourceType = c_char
THOST_FTDC_FSM_Product = '1'
THOST_FTDC_FSM_Exchange = '2'
THOST_FTDC_FSM_All = '3'
TThostFtdcFlexStatModeType = c_char
THOST_FTDC_BIR_Property = '1'
THOST_FTDC_BIR_All = '2'
TThostFtdcByInvestorRangeType = c_char
TThostFtdcSRiskRateType = c_char * 21
TThostFtdcSequenceNo12Type = c_int
THOST_FTDC_PIR_All = '1'
THOST_FTDC_PIR_Property = '2'
THOST_FTDC_PIR_Single = '3'
TThostFtdcPropertyInvestorRangeType = c_char
THOST_FTDC_FIS_NoCreate = '0'
THOST_FTDC_FIS_Created = '1'
THOST_FTDC_FIS_Failed = '2'
TThostFtdcFileStatusType = c_char
THOST_FTDC_FGS_FileTransmit = '0'
THOST_FTDC_FGS_FileGen = '1'
TThostFtdcFileGenStyleType = c_char
THOST_FTDC_SoM_Add = '1'
THOST_FTDC_SoM_Update = '2'
THOST_FTDC_SoM_Delete = '3'
THOST_FTDC_SoM_Copy = '4'
THOST_FTDC_SoM_AcTive = '5'
THOST_FTDC_SoM_CanCel = '6'
THOST_FTDC_SoM_ReSet = '7'
TThostFtdcSysOperModeType = c_char
THOST_FTDC_SoT_UpdatePassword = '0'
THOST_FTDC_SoT_UserDepartment = '1'
THOST_FTDC_SoT_RoleManager = '2'
THOST_FTDC_SoT_RoleFunction = '3'
THOST_FTDC_SoT_BaseParam = '4'
THOST_FTDC_SoT_SetUserID = '5'
THOST_FTDC_SoT_SetUserRole = '6'
THOST_FTDC_SoT_UserIpRestriction = '7'
THOST_FTDC_SoT_DepartmentManager = '8'
THOST_FTDC_SoT_DepartmentCopy = '9'
THOST_FTDC_SoT_Tradingcode = 'A'
THOST_FTDC_SoT_InvestorStatus = 'B'
THOST_FTDC_SoT_InvestorAuthority = 'C'
THOST_FTDC_SoT_PropertySet = 'D'
THOST_FTDC_SoT_ReSetInvestorPasswd = 'E'
THOST_FTDC_SoT_InvestorPersonalityInfo = 'F'
TThostFtdcSysOperTypeType = c_char
THOST_FTDC_CSRCQ_Current = '0'
THOST_FTDC_CSRCQ_History = '1'
TThostFtdcCSRCDataQueyTypeType = c_char
THOST_FTDC_FRS_Normal = '1'
THOST_FTDC_FRS_Freeze = '0'
TThostFtdcFreezeStatusType = c_char
THOST_FTDC_STST_Standard = '0'
THOST_FTDC_STST_NonStandard = '1'
TThostFtdcStandardStatusType = c_char
TThostFtdcCSRCFreezeStatusType = c_char * 2
THOST_FTDC_RPT_Freeze = '1'
THOST_FTDC_RPT_FreezeActive = '2'
THOST_FTDC_RPT_OpenLimit = '3'
THOST_FTDC_RPT_RelieveOpenLimit = '4'
TThostFtdcRightParamTypeType = c_char
TThostFtdcRightTemplateIDType = c_char * 9
TThostFtdcRightTemplateNameType = c_char * 61
THOST_FTDC_AMLDS_Normal = '0'
THOST_FTDC_AMLDS_Deleted = '1'
TThostFtdcDataStatusType = c_char
THOST_FTDC_AMLCHS_Init = '0'
THOST_FTDC_AMLCHS_Checking = '1'
THOST_FTDC_AMLCHS_Checked = '2'
THOST_FTDC_AMLCHS_RefuseReport = '3'
TThostFtdcAMLCheckStatusType = c_char
THOST_FTDC_AMLDT_DrawDay = '0'
THOST_FTDC_AMLDT_TouchDay = '1'
TThostFtdcAmlDateTypeType = c_char
THOST_FTDC_AMLCL_CheckLevel0 = '0'
THOST_FTDC_AMLCL_CheckLevel1 = '1'
THOST_FTDC_AMLCL_CheckLevel2 = '2'
THOST_FTDC_AMLCL_CheckLevel3 = '3'
TThostFtdcAmlCheckLevelType = c_char
TThostFtdcAmlCheckFlowType = c_char * 2
TThostFtdcDataTypeType = c_char * 129
THOST_FTDC_EFT_CSV = '0'
THOST_FTDC_EFT_EXCEL = '1'
THOST_FTDC_EFT_DBF = '2'
TThostFtdcExportFileTypeType = c_char
THOST_FTDC_SMT_Before = '1'
THOST_FTDC_SMT_Settlement = '2'
THOST_FTDC_SMT_After = '3'
THOST_FTDC_SMT_Settlemented = '4'
TThostFtdcSettleManagerTypeType = c_char
TThostFtdcSettleManagerIDType = c_char * 33
TThostFtdcSettleManagerNameType = c_char * 129
THOST_FTDC_SML_Must = '1'
THOST_FTDC_SML_Alarm = '2'
THOST_FTDC_SML_Prompt = '3'
THOST_FTDC_SML_Ignore = '4'
TThostFtdcSettleManagerLevelType = c_char
THOST_FTDC_SMG_Exhcange = '1'
THOST_FTDC_SMG_ASP = '2'
THOST_FTDC_SMG_CSRC = '3'
TThostFtdcSettleManagerGroupType = c_char
TThostFtdcCheckResultMemoType = c_char * 1025
TThostFtdcFunctionUrlType = c_char * 1025
TThostFtdcAuthInfoType = c_char * 129
TThostFtdcAuthCodeType = c_char * 17
THOST_FTDC_LUT_Repeatable = '1'
THOST_FTDC_LUT_Unrepeatable = '2'
TThostFtdcLimitUseTypeType = c_char
THOST_FTDC_DAR_Settle = '1'
THOST_FTDC_DAR_Exchange = '2'
THOST_FTDC_DAR_CSRC = '3'
TThostFtdcDataResourceType = c_char
THOST_FTDC_MGT_ExchMarginRate = '0'
THOST_FTDC_MGT_InstrMarginRate = '1'
THOST_FTDC_MGT_InstrMarginRateTrade = '2'
TThostFtdcMarginTypeType = c_char
THOST_FTDC_ACT_Intraday = '1'
THOST_FTDC_ACT_Long = '2'
TThostFtdcActiveTypeType = c_char
THOST_FTDC_MRT_Exchange = '1'
THOST_FTDC_MRT_Investor = '2'
THOST_FTDC_MRT_InvestorTrade = '3'
TThostFtdcMarginRateTypeType = c_char
THOST_FTDC_BUS_UnBak = '0'
THOST_FTDC_BUS_BakUp = '1'
THOST_FTDC_BUS_BakUped = '2'
THOST_FTDC_BUS_BakFail = '3'
TThostFtdcBackUpStatusType = c_char
THOST_FTDC_SIS_UnInitialize = '0'
THOST_FTDC_SIS_Initialize = '1'
THOST_FTDC_SIS_Initialized = '2'
TThostFtdcInitSettlementType = c_char
THOST_FTDC_SRS_NoCreate = '0'
THOST_FTDC_SRS_Create = '1'
THOST_FTDC_SRS_Created = '2'
THOST_FTDC_SRS_CreateFail = '3'
TThostFtdcReportStatusType = c_char
THOST_FTDC_SSS_UnSaveData = '0'
THOST_FTDC_SSS_SaveDatad = '1'
TThostFtdcSaveStatusType = c_char
THOST_FTDC_SAS_UnArchived = '0'
THOST_FTDC_SAS_Archiving = '1'
THOST_FTDC_SAS_Archived = '2'
THOST_FTDC_SAS_ArchiveFail = '3'
TThostFtdcSettArchiveStatusType = c_char
THOST_FTDC_CTPT_Unkown = '0'
THOST_FTDC_CTPT_MainCenter = '1'
THOST_FTDC_CTPT_BackUp = '2'
TThostFtdcCTPTypeType = c_char
TThostFtdcToolIDType = c_char * 9
TThostFtdcToolNameType = c_char * 81
THOST_FTDC_CDT_Normal = '0'
THOST_FTDC_CDT_SpecFirst = '1'
TThostFtdcCloseDealTypeType = c_char
THOST_FTDC_MFUR_None = '0'
THOST_FTDC_MFUR_Margin = '1'
THOST_FTDC_MFUR_All = '2'
TThostFtdcMortgageFundUseRangeType = c_char
TThostFtdcCurrencyUnitType = c_double
TThostFtdcExchangeRateType = c_double
THOST_FTDC_SPT_CzceHedge = '1'
THOST_FTDC_SPT_IneForeignCurrency = '2'
THOST_FTDC_SPT_DceOpenClose = '3'
TThostFtdcSpecProductTypeType = c_char
THOST_FTDC_FMT_Mortgage = '1'
THOST_FTDC_FMT_Redemption = '2'
TThostFtdcFundMortgageTypeType = c_char
THOST_FTDC_ASPI_BaseMargin = '1'
THOST_FTDC_ASPI_LowestInterest = '2'
TThostFtdcAccountSettlementParamIDType = c_char
TThostFtdcCurrencyNameType = c_char * 31
TThostFtdcCurrencySignType = c_char * 4
THOST_FTDC_FMD_In = '1'
THOST_FTDC_FMD_Out = '2'
TThostFtdcFundMortDirectionType = c_char
THOST_FTDC_BT_Profit = '0'
THOST_FTDC_BT_Loss = '1'
THOST_FTDC_BT_Other = 'Z'
TThostFtdcBusinessClassType = c_char
THOST_FTDC_SST_Manual = '0'
THOST_FTDC_SST_Automatic = '1'
TThostFtdcSwapSourceTypeType = c_char
THOST_FTDC_CED_Settlement = '0'
THOST_FTDC_CED_Sale = '1'
TThostFtdcCurrExDirectionType = c_char
THOST_FTDC_CSS_Entry = '1'
THOST_FTDC_CSS_Approve = '2'
THOST_FTDC_CSS_Refuse = '3'
THOST_FTDC_CSS_Revoke = '4'
THOST_FTDC_CSS_Send = '5'
THOST_FTDC_CSS_Success = '6'
THOST_FTDC_CSS_Failure = '7'
TThostFtdcCurrencySwapStatusType = c_char
TThostFtdcCurrExchCertNoType = c_char * 13
TThostFtdcBatchSerialNoType = c_char * 21
THOST_FTDC_REQF_NoSend = '0'
THOST_FTDC_REQF_SendSuccess = '1'
THOST_FTDC_REQF_SendFailed = '2'
THOST_FTDC_REQF_WaitReSend = '3'
TThostFtdcReqFlagType = c_char
THOST_FTDC_RESF_Success = '0'
THOST_FTDC_RESF_InsuffiCient = '1'
THOST_FTDC_RESF_UnKnown = '8'
TThostFtdcResFlagType = c_char
TThostFtdcPageControlType = c_char * 2
TThostFtdcRecordCountType = c_int
TThostFtdcCurrencySwapMemoType = c_char * 101
THOST_FTDC_EXS_Before = '0'
THOST_FTDC_EXS_After = '1'
TThostFtdcExStatusType = c_char
THOST_FTDC_CR_Domestic = '1'
THOST_FTDC_CR_GMT = '2'
THOST_FTDC_CR_Foreign = '3'
TThostFtdcClientRegionType = c_char
TThostFtdcWorkPlaceType = c_char * 101
TThostFtdcBusinessPeriodType = c_char * 21
TThostFtdcWebSiteType = c_char * 101
TThostFtdcUOAIdCardTypeType = c_char * 3
TThostFtdcClientModeType = c_char * 3
TThostFtdcInvestorFullNameType = c_char * 101
TThostFtdcUOABrokerIDType = c_char * 11
TThostFtdcUOAZipCodeType = c_char * 11
TThostFtdcUOAEMailType = c_char * 101
TThostFtdcOldCityType = c_char * 41
TThostFtdcCorporateIdentifiedCardNoType = c_char * 101
THOST_FTDC_HB_No = '0'
THOST_FTDC_HB_Yes = '1'
TThostFtdcHasBoardType = c_char
THOST_FTDC_SM_Normal = '1'
THOST_FTDC_SM_Emerge = '2'
THOST_FTDC_SM_Restore = '3'
TThostFtdcStartModeType = c_char
THOST_FTDC_TPT_Full = '1'
THOST_FTDC_TPT_Increment = '2'
THOST_FTDC_TPT_BackUp = '3'
TThostFtdcTemplateTypeType = c_char
THOST_FTDC_LM_Trade = '0'
THOST_FTDC_LM_Transfer = '1'
TThostFtdcLoginModeType = c_char
THOST_FTDC_CPT_Instrument = '1'
THOST_FTDC_CPT_Margin = '2'
TThostFtdcPromptTypeType = c_char
TThostFtdcLedgerManageIDType = c_char * 51
TThostFtdcInvestVarietyType = c_char * 101
TThostFtdcBankAccountTypeType = c_char * 2
TThostFtdcLedgerManageBankType = c_char * 101
TThostFtdcCffexDepartmentNameType = c_char * 101
TThostFtdcCffexDepartmentCodeType = c_char * 9
THOST_FTDC_HT_Yes = '1'
THOST_FTDC_HT_No = '0'
TThostFtdcHasTrusteeType = c_char
TThostFtdcCSRCMemo1Type = c_char * 41
TThostFtdcAssetmgrCFullNameType = c_char * 101
TThostFtdcAssetmgrApprovalNOType = c_char * 51
TThostFtdcAssetmgrMgrNameType = c_char * 401
THOST_FTDC_AMT_Bank = '1'
THOST_FTDC_AMT_Securities = '2'
THOST_FTDC_AMT_Fund = '3'
THOST_FTDC_AMT_Insurance = '4'
THOST_FTDC_AMT_Trust = '5'
THOST_FTDC_AMT_Other = '9'
TThostFtdcAmTypeType = c_char
TThostFtdcCSRCAmTypeType = c_char * 5
THOST_FTDC_CFIOT_FundIO = '0'
THOST_FTDC_CFIOT_SwapCurrency = '1'
TThostFtdcCSRCFundIOTypeType = c_char
THOST_FTDC_CAT_Futures = '1'
THOST_FTDC_CAT_AssetmgrFuture = '2'
THOST_FTDC_CAT_AssetmgrTrustee = '3'
THOST_FTDC_CAT_AssetmgrTransfer = '4'
TThostFtdcCusAccountTypeType = c_char
TThostFtdcCSRCNationalType = c_char * 4
TThostFtdcCSRCSecAgentIDType = c_char * 11
THOST_FTDC_LT_Chinese = '1'
THOST_FTDC_LT_English = '2'
TThostFtdcLanguageTypeType = c_char
TThostFtdcAmAccountType = c_char * 23
THOST_FTDC_AMCT_Person = '1'
THOST_FTDC_AMCT_Organ = '2'
THOST_FTDC_AMCT_SpecialOrgan = '4'
TThostFtdcAssetmgrClientTypeType = c_char
THOST_FTDC_ASST_Futures = '3'
THOST_FTDC_ASST_SpecialOrgan = '4'
TThostFtdcAssetmgrTypeType = c_char
TThostFtdcUOMType = c_char * 11
TThostFtdcSHFEInstLifePhaseType = c_char * 3
TThostFtdcSHFEProductClassType = c_char * 11
TThostFtdcPriceDecimalType = c_char * 2
TThostFtdcInTheMoneyFlagType = c_char * 2
THOST_FTDC_CIT_HasExch = '0'
THOST_FTDC_CIT_HasATP = '1'
THOST_FTDC_CIT_HasDiff = '2'
TThostFtdcCheckInstrTypeType = c_char
THOST_FTDC_DT_HandDeliv = '1'
THOST_FTDC_DT_PersonDeliv = '2'
TThostFtdcDeliveryTypeType = c_char
TThostFtdcBigMoneyType = c_double
THOST_FTDC_MMSA_NO = '0'
THOST_FTDC_MMSA_YES = '1'
TThostFtdcMaxMarginSideAlgorithmType = c_char
THOST_FTDC_CACT_Person = '0'
THOST_FTDC_CACT_Company = '1'
THOST_FTDC_CACT_Other = '2'
TThostFtdcDAClientTypeType = c_char
TThostFtdcCombinInstrIDType = c_char * 61
TThostFtdcCombinSettlePriceType = c_char * 61
TThostFtdcDCEPriorityType = c_int
TThostFtdcTradeGroupIDType = c_int
TThostFtdcIsCheckPrepaType = c_int
THOST_FTDC_UOAAT_Futures = '1'
THOST_FTDC_UOAAT_SpecialOrgan = '2'
TThostFtdcUOAAssetmgrTypeType = c_char
THOST_FTDC_DEN_Buy = '0'
THOST_FTDC_DEN_Sell = '1'
TThostFtdcDirectionEnType = c_char
THOST_FTDC_OFEN_Open = '0'
THOST_FTDC_OFEN_Close = '1'
THOST_FTDC_OFEN_ForceClose = '2'
THOST_FTDC_OFEN_CloseToday = '3'
THOST_FTDC_OFEN_CloseYesterday = '4'
THOST_FTDC_OFEN_ForceOff = '5'
THOST_FTDC_OFEN_LocalForceClose = '6'
TThostFtdcOffsetFlagEnType = c_char
THOST_FTDC_HFEN_Speculation = '1'
THOST_FTDC_HFEN_Arbitrage = '2'
THOST_FTDC_HFEN_Hedge = '3'
TThostFtdcHedgeFlagEnType = c_char
THOST_FTDC_FIOTEN_FundIO = '1'
THOST_FTDC_FIOTEN_Transfer = '2'
THOST_FTDC_FIOTEN_SwapCurrency = '3'
TThostFtdcFundIOTypeEnType = c_char
THOST_FTDC_FTEN_Deposite = '1'
THOST_FTDC_FTEN_ItemFund = '2'
THOST_FTDC_FTEN_Company = '3'
THOST_FTDC_FTEN_InnerTransfer = '4'
TThostFtdcFundTypeEnType = c_char
THOST_FTDC_FDEN_In = '1'
THOST_FTDC_FDEN_Out = '2'
TThostFtdcFundDirectionEnType = c_char
THOST_FTDC_FMDEN_In = '1'
THOST_FTDC_FMDEN_Out = '2'
TThostFtdcFundMortDirectionEnType = c_char
TThostFtdcSwapBusinessTypeType = c_char * 3
THOST_FTDC_CP_CallOptions = '1'
THOST_FTDC_CP_PutOptions = '2'
TThostFtdcOptionsTypeType = c_char
THOST_FTDC_STM_Continental = '0'
THOST_FTDC_STM_American = '1'
THOST_FTDC_STM_Bermuda = '2'
TThostFtdcStrikeModeType = c_char
THOST_FTDC_STT_Hedge = '0'
THOST_FTDC_STT_Match = '1'
TThostFtdcStrikeTypeType = c_char
THOST_FTDC_APPT_NotStrikeNum = '4'
TThostFtdcApplyTypeType = c_char
THOST_FTDC_GUDS_Gen = '0'
THOST_FTDC_GUDS_Hand = '1'
TThostFtdcGiveUpDataSourceType = c_char
TThostFtdcExecOrderSysIDType = c_char * 21
THOST_FTDC_OER_NoExec = 'n'
THOST_FTDC_OER_Canceled = 'c'
THOST_FTDC_OER_OK = '0'
THOST_FTDC_OER_NoPosition = '1'
THOST_FTDC_OER_NoDeposit = '2'
THOST_FTDC_OER_NoParticipant = '3'
THOST_FTDC_OER_NoClient = '4'
THOST_FTDC_OER_NoInstrument = '6'
THOST_FTDC_OER_NoRight = '7'
THOST_FTDC_OER_InvalidVolume = '8'
THOST_FTDC_OER_NoEnoughHistoryTrade = '9'
THOST_FTDC_OER_Unknown = 'a'
TThostFtdcExecResultType = c_char
TThostFtdcStrikeSequenceType = c_int
TThostFtdcStrikeTimeType = c_char * 13
THOST_FTDC_COMBT_Future = '0'
THOST_FTDC_COMBT_BUL = '1'
THOST_FTDC_COMBT_BER = '2'
THOST_FTDC_COMBT_STD = '3'
THOST_FTDC_COMBT_STG = '4'
THOST_FTDC_COMBT_PRT = '5'
TThostFtdcCombinationTypeType = c_char
THOST_FTDC_ORPT_PreSettlementPrice = '1'
THOST_FTDC_ORPT_OpenPrice = '4'
TThostFtdcOptionRoyaltyPriceTypeType = c_char
THOST_FTDC_BLAG_Default = '1'
THOST_FTDC_BLAG_IncludeOptValLost = '2'
TThostFtdcBalanceAlgorithmType = c_char
THOST_FTDC_ACTP_Exec = '1'
THOST_FTDC_ACTP_Abandon = '2'
TThostFtdcActionTypeType = c_char
THOST_FTDC_FQST_Submitted = 'a'
THOST_FTDC_FQST_Accepted = 'b'
THOST_FTDC_FQST_Rejected = 'c'
TThostFtdcForQuoteStatusType = c_char
THOST_FTDC_QTST_Unknown = 'a'
THOST_FTDC_QTST_Accepted = 'b'
THOST_FTDC_QTST_Canceled = 'c'
TThostFtdcQuotStatusType = c_char
THOST_FTDC_VM_Absolute = '0'
THOST_FTDC_VM_Ratio = '1'
TThostFtdcValueMethodType = c_char
THOST_FTDC_EOPF_Reserve = '0'
THOST_FTDC_EOPF_UnReserve = '1'
TThostFtdcExecOrderPositionFlagType = c_char
THOST_FTDC_EOCF_AutoClose = '0'
THOST_FTDC_EOCF_NotToClose = '1'
TThostFtdcExecOrderCloseFlagType = c_char
THOST_FTDC_PTE_Futures = '1'
THOST_FTDC_PTE_Options = '2'
TThostFtdcProductTypeType = c_char
THOST_FTDC_CUFN_CUFN_O = 'O'
THOST_FTDC_CUFN_CUFN_T = 'T'
THOST_FTDC_CUFN_CUFN_P = 'P'
THOST_FTDC_CUFN_CUFN_N = 'N'
THOST_FTDC_CUFN_CUFN_L = 'L'
THOST_FTDC_CUFN_CUFN_F = 'F'
THOST_FTDC_CUFN_CUFN_C = 'C'
THOST_FTDC_CUFN_CUFN_M = 'M'
TThostFtdcCZCEUploadFileNameType = c_char
THOST_FTDC_DUFN_DUFN_O = 'O'
THOST_FTDC_DUFN_DUFN_T = 'T'
THOST_FTDC_DUFN_DUFN_P = 'P'
THOST_FTDC_DUFN_DUFN_F = 'F'
THOST_FTDC_DUFN_DUFN_C = 'C'
THOST_FTDC_DUFN_DUFN_D = 'D'
THOST_FTDC_DUFN_DUFN_M = 'M'
THOST_FTDC_DUFN_DUFN_S = 'S'
TThostFtdcDCEUploadFileNameType = c_char
THOST_FTDC_SUFN_SUFN_O = 'O'
THOST_FTDC_SUFN_SUFN_T = 'T'
THOST_FTDC_SUFN_SUFN_P = 'P'
THOST_FTDC_SUFN_SUFN_F = 'F'
TThostFtdcSHFEUploadFileNameType = c_char
THOST_FTDC_CFUFN_SUFN_T = 'T'
THOST_FTDC_CFUFN_SUFN_P = 'P'
THOST_FTDC_CFUFN_SUFN_F = 'F'
THOST_FTDC_CFUFN_SUFN_S = 'S'
TThostFtdcCFFEXUploadFileNameType = c_char
